<a href="https://colab.research.google.com/github/mukeshrock7897/Data-Analysis/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1- install and import library**

# **2- array creation**
  I- Arrays with Predefined Values
* np.array(): Creates an array from any sequence-like object (lists, tuples, etc.).
* np.zeros(): Creates an array filled with zeros.
* np.ones(): Creates an array filled with ones.
* np.full(): Creates an array filled with a specified value.
* np.empty(): Creates an array without initializing its values (faster but values are undefined).
* np.eye(): Creates an identity matrix.
* np.identity(): Same as np.eye(), but more explicit.
* np.diag(): Creates a diagonal array.


II- Arrays with Sequences
* np.arange(): Creates an array with evenly spaced values within a given interval.
* np.linspace(): Creates an array with evenly spaced values within a given interval (including endpoints).
* np.logspace(): Creates an array with logarithmically spaced values.

III- Arrays from Random Numbers
* np.random.rand(): Creates an array of random samples from a uniform distribution over [0, 1).
* np.random.randn(): Creates an array of random samples from a standard normal distribution.
* np.random.randint(): Creates an array of random integers from a low (inclusive) to high (exclusive) integer.
* np.random.uniform(): Creates an array of random samples from a uniform distribution over a specified interval.
* np.random.normal(): Creates an array of random samples from a normal distribution with specified mean and standard deviation.

IV-Additional Functions
* np.frombuffer(): Creates an array from a buffer.
* np.fromfile(): Creates an array from a file.
* np.fromiter(): Creates an array from an iterator.

# **3- NumPy Array Mathematical Functions**
   I-Arithmetic Operations
* Basic operations: +, -, *, /, //, %, **
* np.add(), np.subtract(), np.multiply(), np.divide(), np.floor_divide(), np.mod(), np.power(): Equivalent to the corresponding operators.
* np.absolute() or np.abs(): Calculates the absolute value of each element.
   
  II-Trigonometric Functions
* np.sin(), np.cos(), np.tan(), np.arcsin(), np.arccos(), np.arctan(), np.hypot(), np.arctan2(), np.degrees(), np.radians()

  III-Hyperbolic Functions
* np.sinh(), np.cosh(), np.tanh(), np.arcsinh(), np.arccosh(), np.arctanh()

  IV-Exponential and Logarithmic Functions
* np.exp(), np.expm1(), np.exp2(), np.log(), np.log10(), np.log2(), np.log1p()

  V-Rounding Functions
* np.round(), np.around(), np.rint(), np.fix(), np.floor(), np.ceil(), np.trunc()

 VI-Statistical Functions
* np.mean(), np.median(), np.std(), np.var(), np.min(), np.max(), np.argmin(), np.argmax(), np.sum(), np.prod(), np.cumsum(), np.cumprod(), np.percentile()

 VII-Linear Algebra Functions
* np.dot(), np.matmul(), np.linalg.inv(), np.linalg.det(), np.linalg.eig(), np.linalg.svd(), np.linalg.norm()


# **4- Array Manipulation Functions**
  I-Changing Shape
* reshape(): Reshapes an array without changing its data.
* ravel(): Flattens an array into a one-dimensional array.
* flatten(): Similar to ravel, but returns a copy.
* transpose(): Transposes an array.
* swapaxes(): Interchanges two axes of an array.
* rollaxis(): Rolls an axis to a new location.

  II-Joining Arrays
* concatenate(): Joins arrays along an existing axis.
* vstack(): Stacks arrays vertically (row-wise).
* hstack(): Stacks arrays horizontally (column-wise).
* dstack(): Stacks arrays depth-wise (along the third dimension).
* column_stack(): Creates a 2-D array from 1-D arrays.

  III-Splitting Arrays
* split(): Splits an array into multiple sub-arrays along an axis.
* array_split(): Splits an array into equal or near-equal sub-arrays.
* hsplit(): Splits an array horizontally (column-wise).
* vsplit(): Splits an array vertically (row-wise).

  IV-Adding/Removing Elements
* append(): Appends values to the end of an array.
* insert(): Inserts values into an array at specified positions.
* delete(): Deletes elements from an array.
* resize(): Resizes an array to a new shape.

  V-Other Useful Functions
* copy(): Creates a copy of an array.
* squeeze(): Removes single-dimensional entries from the shape of an array.
* expand_dims(): Inserts a new axis into an array.
* flip(), fliplr(), flipud(): Flips an array in different directions.
* rot90(): Rotates an array by 90 degrees.


# **5-Array Indexing and Slicing**
 I-Basic Slicing
* Array Name with Indices: array_name[start:stop:step]
    * start: Starting index (inclusive).
    * stop: Ending index (exclusive).
    * step: Step size.

II-Advanced Indexing
* Integer Indexing: Using integer arrays to index arrays.
* Boolean Indexing: Using boolean arrays to select elements.

# **5.1- Random Number Generation Functions**
I-Basic Random Number Generation
* np.random.rand(d0, d1, ..., dn): Returns an array of random floats in the half-open interval [0.0, 1.0).
* np.random.randn(d0, d1, ..., dn): Returns an array of random samples from a standard normal distribution.
* np.random.randint(low, high=None, size=None, dtype=int): Returns random integers from low (inclusive) to high (exclusive).
* np.random.uniform(low=0.0, high=1.0, size=None): Returns random floats from a uniform distribution over the specified interval.

II-Permutations
* np.random.shuffle(x): Shuffles the elements of an array in place.
* np.random.permutation(x): Returns a new array with the elements of x permuted.

III- Distributions
* Normal Distribution:
    * np.random.normal(loc=0.0, scale=1.0, size=None)
* Log Normal Distribution:
    * np.random.lognormal(mean=0.0, sigma=1.0, size=None)
* Exponential Distribution:
    * np.random.exponential(scale=1.0, size=None)
* Gamma Distribution:
    * np.random.gamma(shape, scale=1.0, size=None)
* Beta Distribution:
    * np.random.beta(a, b, size=None)
* Binomial Distribution:
    * np.random.binomial(n, p, size=None)
* Poisson Distribution:
    * np.random.poisson(lam=1.0, size=None)
IV- Random Seed
* np.random.seed(seed=None): Sets the seed for the random number generator.


# **6- Searching and Sorting Functions**

I-Sorting Functions
* np.sort(a, axis=-1, kind='quicksort', order=None): Returns a sorted copy of an array.
* np.argsort(a, axis=-1, kind='quicksort', order=None): Returns the indices that would sort an array.
* np.lexsort(keys, axis=-1): Performs an indirect stable sort using a sequence of keys.
* a.sort(axis=-1, kind='quicksort', order=None): Sorts an array in-place.
* np.partition(a, kth, axis=-1, kind='introselect', order=None): Partitions an array into sorted and unsorted regions.
* np.argpartition(a, kth, axis=-1, kind='introselect', order=None): Returns the indices that would partition an array.
II-Searching Functions
* np.argmax(a, axis=None, out=None): Returns the indices of the maximum values along an axis.
* np.argmin(a, axis=None, out=None): Returns the indices of the minimum values along an axis.
* np.nanargmax(a, axis=None): Returns the indices of the maximum values ignoring NaNs.
* np.nanargmin(a, axis=None): Returns the indices of the minimum values ignoring NaNs.
* np.where(condition): Returns elements of an array that satisfy a given condition.
* np.searchsorted(a, v, side='left', sorter=None): Finds indices where to insert new elements to maintain sorted order.

# **7- Fourier Transform Functions**

I-Standard FFTs
* np.fft.fft(a, n=None, axis=-1, norm=None): Computes the one-dimensional discrete Fourier Transform.
* np.fft.ifft(a, n=None, axis=-1, norm=None): Computes the one-dimensional inverse discrete Fourier Transform.
* np.fft.fft2(a, s=None, axes=(-2, -1), norm=None): Computes the two-dimensional discrete Fourier Transform.
* np.fft.ifft2(a, s=None, axes=(-2, -1), norm=None): Computes the two-dimensional inverse discrete Fourier Transform.
* np.fft.fftn(a, s=None, axes=None, norm=None): Computes the N-dimensional discrete Fourier Transform.
* np.fft.ifftn(a, s=None, axes=None, norm=None): Computes the N-dimensional inverse discrete Fourier Transform.

II-Real-Valued FFTs
* np.fft.rfft(a, n=None, axis=-1, norm=None): Computes the one-dimensional discrete Fourier Transform for real input.
* np.fft.irfft(a, n=None, axis=-1, norm=None): Computes the inverse of the one-dimensional discrete Fourier Transform for real output.
* np.fft.rfft2(a, s=None, axes=(-2, -1), norm=None): Computes the two-dimensional discrete Fourier Transform for real input.
* np.fft.irfft2(a, s=None, axes=(-2, -1), norm=None): Computes the inverse of the two-dimensional discrete Fourier Transform for real output.
* np.fft.rfftn(a, s=None, axes=None, norm=None): Computes the N-dimensional discrete Fourier Transform for real input.
* np.fft.irfftn(a, s=None, axes=None, norm=None): Computes the inverse of the N-dimensional discrete Fourier Transform for real output.

III-Other Useful Functions
* np.fft.fftfreq(n, d=1.0): Returns the Discrete Fourier Transform sample frequencies.
* np.fft.rfftfreq(n, d=1.0): Returns the Discrete Fourier Transform sample frequencies for real input.
* np.fft.fftshift(x, axes=None): Shifts the zero-frequency component to the center of the spectrum.
* np.fft.ifftshift(x, axes=None): The inverse of fftshift.

# **8- NumPy Functions for Data Type Handling**

I-Data Type Inspection
* np.dtype(obj): Creates a data type object.
* ndarray.dtype: Returns the data type of an array.
* np.issubdtype(a, b): Checks if one data type is a subtype of another.

II-Data Type Conversion
* ndarray.astype(dtype): Casts an array to a specified data type.
* np.array(obj, dtype=None): Creates an array with a specified data type.
* np.cast[dtype](x): Casts an array to a specified data type.

III-Data Type Information
* np.sctypeDict: Dictionary mapping dtype chars to scalar types.
* np.typeDict: Dictionary mapping dtype chars to type names.
* np.find_common_type(arrays): Finds a common data type for multiple arrays.

# **9- NumPy Functions for Padding and Trimming**

I-Padding
* np.pad(array, pad_width, mode='constant', **kwargs): Adds padding to the edges of an array.
    * pad_width: Specifies the number of values to pad on each side of the array.
    * mode: Determines the padding method (e.g., 'constant', 'edge', 'reflect', 'symmetric').
    * kwargs: Additional arguments for specific padding modes.

II-Trimming
* np.trim_zeros(arr, trim='fb'): Removes leading and/or trailing zeros from an array.
    * trim: Specifies which edges to trim ('f' for front, 'b' for back).

# **10-NumPy Functions for Polynomial Operations**

I-Core Polynomial Functions
* np.poly1d(coeffs): Creates a polynomial object from a list of coefficients.
* np.polyval(p, x): Evaluates a polynomial at specified values.
* np.polyfit(x, y, deg, rcond=None, full=False, w=None, cov=False): Fits a polynomial to data, returning the coefficients.
* np.polyder(p, m=1): Computes the derivative of a polynomial.
* np.polyint(p, m=1, k=0): Computes the integral of a polynomial.
* np.roots(p): Finds the roots of a polynomial.

II-Additional Functions
* np.polyadd(p1, p2): Adds two polynomials.
* np.polysub(p1, p2): Subtracts one polynomial from another.
* np.polymul(p1, p2): Multiplies two polynomials.
* np.polydiv(p1, p2): Divides two polynomials.


# **11- NumPy Functions for Interpolation and Extrapolation**
I. np.interp(x, xp, fp, left=None, right=None, period=None):
* Performs one-dimensional linear interpolation.
* x: Points at which to interpolate.
* xp: x-coordinates of the data points.
* fp: y-coordinates of the data points.
* left, right: Values to return for extrapolation.
* period: Period of the data for periodic interpolation.
II. np.polyfit(x, y, deg, rcond=None, full=False, w=None, cov=False):


# **12- Numpy Functions for Financial Operations**
NumPy-Financial: This library offers functions like npf.fv, npf.pv, npf.rate, npf.pmt, etc., which are similar to Excel's financial functions.


# **13- NumPy Functions Useful for Signal Processing**
I- np.convolve: Computes the discrete convolution of two one-dimensional sequences.
II- np.correlate: Computes the correlation of two one-dimensional sequences.

# **13- Sharing Memories**
np.shares_memory() and np.may_share_memory()



# **1. Install and Import Library**

**Installation**

In [161]:
!pip install numpy

**Importing NumPy**

In [162]:
import numpy as np

# Creating a NumPy array
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


# **2. Array Creation**
**I-Arrays with Predefined Values**
* **np.array():** Creates an array from any sequence-like object (lists, tuples, etc.).

In [163]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


* **np.zeros():** Creates an array filled with zeros.

In [164]:
zeros = np.zeros((3, 3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


* **np.ones():** Creates an array filled with ones.

In [165]:
ones = np.ones((2, 2))
print(ones)

[[1. 1.]
 [1. 1.]]


* **np.full():** Creates an array filled with a specified value.

In [166]:
full = np.full((2, 3), 7)
print(full)

[[7 7 7]
 [7 7 7]]


* **np.empty():** Creates an array without initializing its values (faster but values are undefined).

In [167]:
empty = np.empty((3, 3))
print(empty)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


* **np.eye():** Creates an identity matrix.

In [168]:
eye = np.eye(3)
print(eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


* **np.identity():** Same as **np.eye()**, but more explicit.

In [169]:
identity = np.identity(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


* **np.diag():** Creates a diagonal array.

In [170]:
diag = np.diag([1, 2, 3, 4])
print(diag)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


**II. Arrays with Sequences**

* **np.arange():** Creates an array with evenly spaced values within a given interval.

In [171]:
arange_arr = np.arange(0, 10, 2)
print(arange_arr)

[0 2 4 6 8]


* **np.linspace():** Creates an array with evenly spaced values within a given interval (including endpoints).

In [172]:
linspace_arr = np.linspace(0, 1, 5)
print(linspace_arr)

[0.   0.25 0.5  0.75 1.  ]


* **np.logspace():** Creates an array with logarithmically spaced values.

In [173]:
logspace_arr = np.logspace(1, 3, 4)
print(logspace_arr)

[  10.           46.41588834  215.443469   1000.        ]


**III. Arrays from Random Numbers**
* **np.random.rand():** Creates an array of random samples from a uniform distribution over [0, 1).

In [174]:
rand_uniform = np.random.rand(3, 3)
print(rand_uniform)

[[0.10864574 0.06019599 0.26985925]
 [0.99583958 0.39930632 0.40979801]
 [0.19020773 0.16001398 0.17153795]]


* **np.random.randn():** Creates an array of random samples from a standard normal distribution.

In [175]:
rand_normal = np.random.randn(3, 3)
print(rand_normal)

[[ 0.39456347  1.49734751  1.69436014]
 [-0.21283751  0.10245038  1.59343286]
 [ 0.36274775  1.11227325  0.60074712]]


* **np.random.randint():** Creates an array of random integers from a low (inclusive) to high (exclusive) integer.

In [176]:
rand_int = np.random.randint(0, 10, size=(3, 3))
print(rand_int)

[[4 8 2]
 [3 5 1]
 [1 1 5]]


* **np.random.uniform():** Creates an array of random samples from a uniform distribution over a specified interval.

In [177]:
rand_uniform_interval = np.random.uniform(1, 5, size=(3, 3))
print(rand_uniform_interval)

[[1.50811895 2.30468966 4.28376725]
 [4.24741016 3.48357607 2.60764448]
 [2.98134296 2.60860723 1.31902228]]


* **np.random.normal():** Creates an array of random samples from a normal distribution with specified mean and standard deviation.

In [178]:
rand_normal_dist = np.random.normal(loc=0.0, scale=1.0, size=(3, 3))
print(rand_normal_dist)

[[ 0.24170607  0.42466595 -0.37202391]
 [ 0.7059552   0.25703186 -1.41647115]
 [-1.1684571   0.18353561 -0.00674324]]


**IV. Additional Functions**

* **np.frombuffer():** Creates an array from a buffer.

In [179]:
buffer = b'Hello World'
buffer_arr = np.frombuffer(buffer, dtype='S1')
print(buffer_arr)

[b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']


* **np.fromfile():** Creates an array from a file.

In [180]:
# Assuming 'data.bin' contains binary data, let's first create it:
!echo "Sample binary data" > data.bin

file_arr = np.fromfile('data.bin', dtype=np.int32)
print(file_arr)


[1886216531 1646290284 1918987881 1633951865]


* **np.fromiter():** Creates an array from an iterator.

In [181]:
iterable = (x*x for x in range(5))
iter_arr = np.fromiter(iterable, dtype=int)
print(iter_arr)

[ 0  1  4  9 16]


# **3. NumPy Array Mathematical Functions**

**I. Arithmetic Operations**
* Basic operations:` +, -, *, /, //, %, ** `

In [182]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
add = arr1 + arr2
subtract = arr1 - arr2
multiply = arr1 * arr2
divide = arr1 / arr2
floor_divide = arr1 // arr2
mod = arr1 % arr2
power = arr1 ** arr2
print(add, subtract, multiply, divide, floor_divide, mod, power)


[5 7 9] [-3 -3 -3] [ 4 10 18] [0.25 0.4  0.5 ] [0 0 0] [1 2 3] [  1  32 729]


* **np.add():** Equivalent to +



In [183]:
result = np.add(arr1, arr2)
print(result)

[5 7 9]


* **np.subtract():** Equivalent to `-`

In [184]:
result = np.subtract(arr1, arr2)
print(result)

[-3 -3 -3]


* **np.multiply():** Equivalent to `*`

In [185]:
result = np.multiply(arr1, arr2)
print(result)

[ 4 10 18]


* **np.divide():** Equivalent to `/`

In [186]:
result = np.divide(arr1, arr2)
print(result)

[0.25 0.4  0.5 ]


* **np.floor_divide():** Equivalent to `//`

In [187]:
result = np.floor_divide(arr1, arr2)
print(result)

[0 0 0]


* **np.mod():** Equivalent to `%`

In [188]:
result = np.mod(arr1, arr2)
print(result)

[1 2 3]


* **np.power():** Equivalent to `**`

In [189]:
result = np.power(arr1, arr2)
print(result)

[  1  32 729]


* **np.absolute() or np.abs():** Calculates the absolute value of each element.

In [190]:
arr = np.array([-1, -2, -3])
result = np.abs(arr)
print(result)

[1 2 3]


**II. Trigonometric Functions**
* **np.sin(), np.cos(), np.tan():** Compute trigonometric sine, cosine, and tangent.

In [191]:
angles = np.array([0, np.pi/2, np.pi])
sine = np.sin(angles)
cosine = np.cos(angles)
tangent = np.tan(angles)
print(sine, cosine, tangent)

[0.0000000e+00 1.0000000e+00 1.2246468e-16] [ 1.000000e+00  6.123234e-17 -1.000000e+00] [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


* **np.arcsin(), np.arccos(), np.arctan():** Inverse trigonometric functions.

In [192]:
sine_values = np.array([0, 1, -1])
arcsine = np.arcsin(sine_values)
arccosine = np.arccos(sine_values)
arctangent = np.arctan(sine_values)
print(arcsine, arccosine, arctangent)

[ 0.          1.57079633 -1.57079633] [1.57079633 0.         3.14159265] [ 0.          0.78539816 -0.78539816]


* **np.hypot():** Calculate the hypotenuse.

In [193]:
hypot = np.hypot(3, 4)
print(hypot)

5.0


* **np.arctan2():** Compute arctangent of two variables.

In [194]:
arctan2 = np.arctan2(1, 1)
print(arctan2)

0.7853981633974483


* **np.degrees():** Convert radians to degrees.

In [195]:
degrees = np.degrees(np.pi)
print(degrees)

180.0


* **np.radians():** Convert degrees to radians.

In [196]:
radians = np.radians(180)
print(radians)

3.141592653589793


**III. Hyperbolic Functions**
* **np.sinh(), np.cosh(), np.tanh():** Compute hyperbolic sine, cosine, and tangent.

In [197]:
values = np.array([0, np.pi/2, np.pi])
sinh = np.sinh(values)
cosh = np.cosh(values)
tanh = np.tanh(values)
print(sinh, cosh, tanh)

[ 0.          2.3012989  11.54873936] [ 1.          2.50917848 11.59195328] [0.         0.91715234 0.99627208]


* **np.arcsinh(), np.arccosh(), np.arctanh():** Inverse hyperbolic functions.

In [198]:
sinh_values = np.array([0, 1, -1])
arcsinh = np.arcsinh(sinh_values)
arccosh = np.arccosh([1, 2])
arctanh = np.arctanh([0.5, -0.5])
print(arcsinh, arccosh, arctanh)

[ 0.          0.88137359 -0.88137359] [0.        1.3169579] [ 0.54930614 -0.54930614]


**IV. Exponential and Logarithmic Functions**
* **np.exp():** Compute the exponential of all elements.

In [199]:
arr = np.array([1, 2, 3])
exp = np.exp(arr)
print(exp)

[ 2.71828183  7.3890561  20.08553692]


* **np.expm1():** Compute `exp(x) - 1` for all elements.

In [200]:
expm1 = np.expm1(arr)
print(expm1)

[ 1.71828183  6.3890561  19.08553692]


* **np.exp2():** Compute `2**x` for all elements.

In [201]:
exp2 = np.exp2(arr)
print(exp2)

[2. 4. 8.]


* **np.log():** Compute the natural logarithm of all elements.

In [202]:
log = np.log(arr)
print(log)

[0.         0.69314718 1.09861229]


* **np.log10():** Compute the base-10 logarithm of all elements.

In [203]:
log10 = np.log10(arr)
print(log10)

[0.         0.30103    0.47712125]


* **np.log2():** Compute the base-2 logarithm of all elements.

In [204]:
log2 = np.log2(arr)
print(log2)

[0.        1.        1.5849625]


* **np.log1p():** Compute `log(1 + x)` for all elements.

In [205]:
log1p = np.log1p(arr)
print(log1p)

[0.69314718 1.09861229 1.38629436]


**V. Rounding Functions**
* **np.round(), np.around():** Round elements to the nearest integer.

In [206]:
arr = np.array([1.5, 2.7, 3.3])
rounded = np.round(arr)
print(rounded)

[2. 3. 3.]


* **np.rint():** Round elements to the nearest integer (ties rounded to even).

In [207]:
rint = np.rint(arr)
print(rint)

[2. 3. 3.]


* **np.fix():** Round elements towards zero.

In [208]:
fix = np.fix(arr)
print(fix)

[1. 2. 3.]


* **np.floor():** Compute the floor of each element.

In [209]:
floor = np.floor(arr)
print(floor)

[1. 2. 3.]


* **np.ceil():** Compute the ceiling of each element.

In [210]:
ceil = np.ceil(arr)
print(ceil)

[2. 3. 4.]


* **np.trunc():** Truncate each element (remove fractional part).

In [211]:
trunc = np.trunc(arr)
print(trunc)

[1. 2. 3.]


**VI. Statistical Functions**
* **np.mean():** Compute the arithmetic mean.

In [212]:
arr = np.array([1, 2, 3, 4, 5])
mean = np.mean(arr)
print(mean)

3.0


* **np.median():** Compute the median.



In [213]:
median = np.median(arr)
print(median)

3.0


* **np.std():** Compute the standard deviation.

In [214]:
std = np.std(arr)
print(std)

1.4142135623730951


* **np.var():** Compute the variance.

In [215]:
var = np.var(arr)
print(var)

2.0


* **np.min():** Find the minimum value.

In [216]:
min_val = np.min(arr)
print(min_val)

1


* **np.max():** Find the maximum value.



In [217]:
max_val = np.max(arr)
print(max_val)

5


* **np.argmin():** Find the index of the minimum value.

In [218]:
argmin = np.argmin(arr)
print(argmin)

0


* **np.argmax():** Find the index of the maximum value.

In [219]:
argmax = np.argmax(arr)
print(argmax)

4


* **np.sum():** Compute the sum of all elements.

In [220]:
total_sum = np.sum(arr)
print(total_sum)

15


* **np.prod():** Compute the product of all elements.

In [221]:
total_prod = np.prod(arr)
print(total_prod)

120


* **np.cumsum():** Compute the cumulative sum.

In [222]:
cumsum = np.cumsum(arr)
print(cumsum)

[ 1  3  6 10 15]


* **np.cumprod():** Compute the cumulative product.

In [223]:
cumprod = np.cumprod(arr)
print(cumprod)

[  1   2   6  24 120]


* **np.percentile():** Compute the percentile of the array elements.

In [224]:
percentile = np.percentile(arr, 50)
print(percentile)

3.0


# **4. Array Manipulation Functions**

**I. Changing Shape**
* **reshape():** Reshapes an array without changing its data.

In [225]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape((2, 3))
print(reshaped)

[[1 2 3]
 [4 5 6]]


* **ravel():** Flattens an array into a one-dimensional array.

In [226]:
raveled = reshaped.ravel()
print(raveled)

[1 2 3 4 5 6]


* **flatten():** Similar to ravel, but returns a copy.

In [227]:
flattened = reshaped.flatten()
print(flattened)

[1 2 3 4 5 6]


* **transpose():** Transposes an array.

In [228]:
transposed = reshaped.transpose()
print(transposed)

[[1 4]
 [2 5]
 [3 6]]


* **swapaxes():** Interchanges two axes of an array.

In [229]:
arr = np.array([[1, 2, 3]])
swapped = np.swapaxes(arr, 0, 1)
print(swapped)

[[1]
 [2]
 [3]]


* **rollaxis():** Rolls an axis to a new location.

In [230]:
arr = np.ones((3, 4, 5))
rolled = np.rollaxis(arr, 2, 0)
print(rolled.shape)

(5, 3, 4)


**II. Joining Arrays**
* **concatenate():** Joins arrays along an existing axis.

In [231]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])
concatenated = np.concatenate((arr1, arr2), axis=0)
print(concatenated)

[[1 2]
 [3 4]
 [5 6]]


* **vstack():** Stacks arrays vertically (row-wise).

In [232]:
vstacked = np.vstack((arr1, arr2))
print(vstacked)

[[1 2]
 [3 4]
 [5 6]]


* **hstack():** Stacks arrays horizontally (column-wise).

In [233]:
arr3 = np.array([[5], [6]])
hstacked = np.hstack((arr1, arr3))
print(hstacked)

[[1 2 5]
 [3 4 6]]


* **dstack():** Stacks arrays depth-wise (along the third dimension).

In [234]:
arr4 = np.array([[7, 8], [9, 10]])
dstacked = np.dstack((arr1, arr4))
print(dstacked)

[[[ 1  7]
  [ 2  8]]

 [[ 3  9]
  [ 4 10]]]


* **column_stack():** Creates a 2-D array from 1-D arrays.

In [235]:
arr5 = np.array([1, 2, 3])
arr6 = np.array([4, 5, 6])
column_stacked = np.column_stack((arr5, arr6))
print(column_stacked)

[[1 4]
 [2 5]
 [3 6]]


**III. Splitting Arrays**
* **split():** Splits an array into multiple sub-arrays along an axis.

In [236]:
arr = np.array([1, 2, 3, 4, 5, 6])
split_arr = np.split(arr, 3)
print(split_arr)

[array([1, 2]), array([3, 4]), array([5, 6])]


* **array_split():** Splits an array into equal or near-equal sub-arrays.

In [237]:
split_arr = np.array_split(arr, 4)
print(split_arr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


* **hsplit():** Splits an array horizontally (column-wise).

In [238]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
hsplit_arr = np.hsplit(arr, 3)
print(hsplit_arr)

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


* **vsplit():** Splits an array vertically (row-wise).

In [239]:
vsplit_arr = np.vsplit(arr, 2)
print(vsplit_arr)

[array([[1, 2, 3]]), array([[4, 5, 6]])]


**IV. Adding/Removing Elements**
* **append():** Appends values to the end of an array.

In [240]:
arr = np.array([1, 2, 3])
appended = np.append(arr, [4, 5, 6])
print(appended)

[1 2 3 4 5 6]


* **insert():** Inserts values into an array at specified positions.

In [241]:
inserted = np.insert(arr, 1, [7, 8])
print(inserted)

[1 7 8 2 3]


* **delete():** Deletes elements from an array.

In [242]:
deleted = np.delete(arr, [1])
print(deleted)

[1 3]


* **resize():** Resizes an array to a new shape.

In [243]:
resized = np.resize(arr, (2, 3))
print(resized)

[[1 2 3]
 [1 2 3]]


**V. Other Useful Functions**
* **copy():** Creates a copy of an array.

In [244]:
copied = arr.copy()
print(copied)

[1 2 3]


* **squeeze():** Removes single-dimensional entries from the shape of an array.

In [245]:
arr = np.array([[[1, 2, 3]], [[4, 5, 6]]])
squeezed = np.squeeze(arr)
print(squeezed)

[[1 2 3]
 [4 5 6]]


* **expand_dims():** Inserts a new axis into an array.

In [246]:
expanded = np.expand_dims(arr, axis=1)
print(expanded)

[[[[1 2 3]]]


 [[[4 5 6]]]]


* **flip(), fliplr(), flipud():** Flips an array in different directions.

In [247]:
arr = np.array([[1, 2], [3, 4]])
flipped = np.flip(arr)
fliplr = np.fliplr(arr)
flipud = np.flipud(arr)
print(flipped, fliplr, flipud)

[[4 3]
 [2 1]] [[2 1]
 [4 3]] [[3 4]
 [1 2]]


* **rot90():** Rotates an array by 90 degrees.

In [248]:
rotated = np.rot90(arr)
print(rotated)

[[2 4]
 [1 3]]


# **5. Array Indexing and Slicing**

**I. Basic Slicing**

Array Name with Indices: array_name[start:stop:step]

* `start`: Starting index (inclusive).
* `stop`: Ending index (exclusive).
* `step`: Step size.

In [249]:
arr = np.array([0, 1, 2, 3, 4, 5])
sliced = arr[1:5:2]  # Output: [1, 3]
print(sliced)

[1 3]


**II. Advanced Indexing**
* **Integer Indexing:** Using integer arrays to index arrays.

In [250]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
indexed = arr[[0, 1, 2], [0, 1, 0]]  # Output: [1, 4, 5]
print(indexed)

[1 4 5]


* **Boolean Indexing:** Using boolean arrays to select elements.

In [251]:
arr = np.array([0, 1, 2, 3, 4, 5])
bool_idx = arr > 2  # Output: [False, False, False, True, True, True]
filtered = arr[bool_idx]  # Output: [3, 4, 5]
print(filtered)

[3 4 5]


# **5.1 Random Number Generation Functions**

**I. Basic Random Number Generation**
* **np.random.rand(d0, d1, ..., dn):** Returns an array of random floats in the half-open interval [0.0, 1.0).

In [252]:
random_floats = np.random.rand(2, 3)
print(random_floats)

[[0.90418342 0.05817252 0.92806135]
 [0.65939015 0.11337911 0.25340411]]


* **np.random.randn(d0, d1, ..., dn):** Returns an array of random samples from a standard normal distribution.

In [253]:
random_normal = np.random.randn(2, 3)
print(random_normal)

[[ 0.99251617 -1.80531887  0.04358461]
 [ 1.0459847  -0.87208058  0.7035664 ]]


* **np.random.randint(low, high=None, size=None, dtype=int):** Returns random integers from low (inclusive) to high (exclusive).



In [254]:
random_integers = np.random.randint(1, 10, size=(2, 3))
print(random_integers)

[[5 1 1]
 [6 9 4]]


* **np.random.uniform(low=0.0, high=1.0, size=None):** Returns random floats from a uniform distribution over the specified interval.

In [255]:
random_uniform = np.random.uniform(1.0, 3.0, size=(2, 3))
print(random_uniform)

[[2.60156745 1.81024739 1.32059722]
 [2.52376089 1.43792674 1.98963572]]


**II. Permutations**
* **np.random.shuffle(x):** Shuffles the elements of an array in place.

In [256]:
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print(arr)

[2 1 3 5 4]


* **np.random.permutation(x):** Returns a new array with the elements of x permuted.

In [257]:
arr = np.array([1, 2, 3, 4, 5])
permuted = np.random.permutation(arr)
print(permuted)

[3 2 1 4 5]


**III. Distributions**
* **Normal Distribution:** np.random.normal(loc=0.0, scale=1.0, size=None)

In [258]:
normal_dist = np.random.normal(loc=0.0, scale=1.0, size=(2, 3))
print(normal_dist)

[[ 0.19542302  1.15910964  0.82427986]
 [-1.2197194   1.19810555 -0.17890181]]


* **Log Normal Distribution:** np.random.lognormal(mean=0.0, sigma=1.0, size=None)

In [259]:
lognormal_dist = np.random.lognormal(mean=0.0, sigma=1.0, size=(2, 3))
print(lognormal_dist)

[[2.88549564 3.26163263 1.1488909 ]
 [7.54284927 1.5343703  0.14767958]]


* **Exponential Distribution:** np.random.exponential(scale=1.0, size=None)

In [260]:
exponential_dist = np.random.exponential(scale=1.0, size=(2, 3))
print(exponential_dist)

[[0.70799383 1.78394339 1.97334795]
 [2.37295534 3.40938751 0.59972185]]


* **Gamma Distribution:** np.random.gamma(shape, scale=1.0, size=None)

In [261]:
gamma_dist = np.random.gamma(shape=2.0, scale=1.0, size=(2, 3))
print(gamma_dist)

[[0.89614104 1.05382678 0.54233943]
 [2.22727977 1.35057832 3.28960071]]


* **Beta Distribution:** np.random.beta(a, b, size=None)

In [262]:
beta_dist = np.random.beta(a=0.5, b=0.5, size=(2, 3))
print(beta_dist)

[[0.1899272  0.02738553 0.49229866]
 [0.80091866 0.00364589 0.72668908]]


* **Binomial Distribution:** np.random.binomial(n, p, size=None)

In [263]:
binomial_dist = np.random.binomial(n=10, p=0.5, size=(2, 3))
print(binomial_dist)

[[4 7 5]
 [5 5 6]]


* **Poisson Distribution:** np.random.poisson(lam=1.0, size=None)

In [264]:
poisson_dist = np.random.poisson(lam=3.0, size=(2, 3))
print(poisson_dist)

[[2 2 1]
 [4 4 4]]


**IV. Random Seed**
* **np.random.seed(seed=None):** Sets the seed for the random number generator.

# **6. Searching and Sorting Functions**

**I. Sorting Functions**
* **np.sort(a, axis=-1, kind='quicksort', order=None):** Returns a sorted copy of an array.

In [265]:
arr = np.array([[3, 2, 1], [6, 5, 4]])
sorted_arr = np.sort(arr, axis=1)
print(sorted_arr)

[[1 2 3]
 [4 5 6]]


* **np.argsort(a, axis=-1, kind='quicksort', order=None):** Returns the indices that would sort an array.

In [266]:
arr = np.array([3, 2, 1])
argsorted_indices = np.argsort(arr)
print(argsorted_indices)

[2 1 0]


* **np.lexsort(keys, axis=-1):** Performs an indirect stable sort using a sequence of keys.

In [267]:
keys = np.array([[1, 0, 3], [0, 2, 2]])
lexsorted_indices = np.lexsort(keys)
print(lexsorted_indices)

[0 1 2]


* **a.sort(axis=-1, kind='quicksort', order=None):** Sorts an array in-place.

In [268]:
arr = np.array([3, 2, 1])
arr.sort()
print(arr)

[1 2 3]


* **np.partition(a, kth, axis=-1, kind='introselect', order=None):** Partitions an array into sorted and unsorted regions.

In [269]:
arr = np.array([3, 4, 2, 1])
partitioned = np.partition(arr, 2)
print(partitioned)

[1 2 3 4]


* **np.argpartition(a, kth, axis=-1, kind='introselect', order=None):** Returns the indices that would partition an array.

In [270]:
arr = np.array([3, 4, 2, 1])
argpartitioned = np.argpartition(arr, 2)
print(argpartitioned)

[3 2 0 1]


**II. Searching Functions**
* **np.argmax(a, axis=None, out=None):** Returns the indices of the maximum values along an axis.

In [271]:
arr = np.array([1, 3, 2])
max_index = np.argmax(arr)
print(max_index)

1


* **np.argmin(a, axis=None, out=None):** Returns the indices of the minimum values along an axis.

In [272]:
arr = np.array([1, 3, 2])
min_index = np.argmin(arr)
print(min_index)

0


* **np.nanargmax(a, axis=None):** Returns the indices of the maximum values ignoring NaNs.

In [273]:
arr = np.array([np.nan, 2, 3, np.nan])
max_index = np.nanargmax(arr)
print(max_index)

2


* **np.nanargmin(a, axis=None):** Returns the indices of the minimum values ignoring NaNs

In [274]:
arr = np.array([np.nan, 2, 1, np.nan])
min_index = np.nanargmin(arr)
print(min_index)

2


* **np.where(condition):** Returns elements of an array that satisfy a given condition.

In [275]:
arr = np.array([1, 2, 3, 4, 5])
condition = arr > 3
filtered_indices = np.where(condition)
print(filtered_indices)

(array([3, 4]),)


* **np.searchsorted(a, v, side='left', sorter=None):** Finds indices where to insert new elements to maintain sorted order.

In [276]:
arr = np.array([1, 2, 4, 5])
indices = np.searchsorted(arr, [3])
print(indices)

[2]


# **7. Fourier Transform Functions**

**I. Standard FFTs**
* **np.fft.fft(a, n=None, axis=-1, norm=None):** Computes the one-dimensional discrete Fourier Transform.

In [277]:
import numpy as np
a = np.array([1, 2, 3, 4])
fft = np.fft.fft(a)
print(fft)  # Output: [10.+0.j -2.+2.j -2.+0.j -2.-2.j]

[10.+0.j -2.+2.j -2.+0.j -2.-2.j]


* **np.fft.ifft(a, n=None, axis=-1, norm=None):** Computes the one-dimensional inverse discrete Fourier Transform.

In [278]:
ifft = np.fft.ifft(fft)
print(ifft)  # Output: [1.+0.j 2.+0.j 3.+0.j 4.+0.j]

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


* **np.fft.fft2(a, s=None, axes=(-2, -1), norm=None):** Computes the two-dimensional discrete Fourier Transform.

In [279]:
a = np.array([[1, 2], [3, 4]])
fft2 = np.fft.fft2(a)
print(fft2)  # Output: [[10.+0.j -2.+0.j] [-4.+0.j  0.+0.j]]


[[10.+0.j -2.+0.j]
 [-4.+0.j  0.+0.j]]


* **np.fft.ifft2(a, s=None, axes=(-2, -1), norm=None):** Computes the two-dimensional inverse discrete Fourier Transform.

In [280]:
ifft2 = np.fft.ifft2(fft2)
print(ifft2)  # Output: [[1.+0.j 2.+0.j] [3.+0.j 4.+0.j]]

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


* **np.fft.fftn(a, s=None, axes=None, norm=None):** Computes the N-dimensional discrete Fourier Transform.

In [281]:
a = np.array([[1, 2], [3, 4]])
fftn = np.fft.fftn(a)
print(fftn)  # Output: [[10.+0.j -2.+0.j] [-4.+0.j  0.+0.j]]

[[10.+0.j -2.+0.j]
 [-4.+0.j  0.+0.j]]


* **np.fft.ifftn(a, s=None, axes=None, norm=None):** Computes the N-dimensional inverse discrete Fourier Transform.



In [282]:
ifftn = np.fft.ifftn(fftn)
print(ifftn)  # Output: [[1.+0.j 2.+0.j] [3.+0.j 4.+0.j]]

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


**II. Real-Valued FFTs**
* **np.fft.rfft(a, n=None, axis=-1, norm=None):** Computes the one-dimensional discrete Fourier Transform for real input.

In [283]:
a = np.array([1, 2, 3, 4])
rfft = np.fft.rfft(a)
print(rfft)  # Output: [10.+0.j -2.+2.j]

[10.+0.j -2.+2.j -2.+0.j]


* **np.fft.irfft(a, n=None, axis=-1, norm=None):** Computes the inverse of the one-dimensional discrete Fourier Transform for real output.

In [284]:
irfft = np.fft.irfft(rfft)
print(irfft)  # Output: [1. 2. 3. 4.]

[1. 2. 3. 4.]


* **np.fft.rfft2(a, s=None, axes=(-2, -1), norm=None):** Computes the two-dimensional discrete Fourier Transform for real input.

In [285]:
a = np.array([[1, 2], [3, 4]])
rfft2 = np.fft.rfft2(a)
print(rfft2)  # Output: [[10.+0.j -2.+0.j] [-4.+0.j  0.+0.j]]


[[10.+0.j -2.+0.j]
 [-4.+0.j  0.+0.j]]


* **np.fft.rfft2(a, s=None, axes=(-2, -1), norm=None):** Computes the two-dimensional discrete Fourier Transform for real input.

In [286]:
irfft2 = np.fft.irfft2(rfft2)
print(irfft2)  # Output: [[1. 2.] [3. 4.]]

[[1. 2.]
 [3. 4.]]


* **np.fft.rfftn(a, s=None, axes=None, norm=None):** Computes the N-dimensional discrete Fourier Transform for real input.

In [287]:
a = np.array([[1, 2], [3, 4]])
rfftn = np.fft.rfftn(a)
print(rfftn)  # Output: [[10.+0.j -2.+0.j] [-4.+0.j  0.+0.j]]

[[10.+0.j -2.+0.j]
 [-4.+0.j  0.+0.j]]


* **np.fft.irfftn(a, s=None, axes=None, norm=None):** Computes the inverse of the N-dimensional discrete Fourier Transform for real output.

In [288]:
irfftn = np.fft.irfftn(rfftn)
print(irfftn)  # Output: [[1. 2.] [3. 4.]]

[[1. 2.]
 [3. 4.]]


**III. Other Useful Functions**
* **np.fft.fftfreq(n, d=1.0):** Returns the Discrete Fourier Transform sample frequencies.

In [289]:
n = 4
freqs = np.fft.fftfreq(n)
print(freqs)  # Output: [ 0.    0.25 -0.5  -0.25]

[ 0.    0.25 -0.5  -0.25]


* **np.fft.rfftfreq(n, d=1.0):** Returns the Discrete Fourier Transform sample frequencies for real input.

In [290]:
n = 4
rfftfreqs = np.fft.rfftfreq(n)
print(rfftfreqs)  # Output: [0.  0.25 0.5 ]

[0.   0.25 0.5 ]


* **np.fft.fftshift(x, axes=None):** Shifts the zero-frequency component to the center of the spectrum.

In [291]:
x = np.array([1, 2, 3, 4])
shifted = np.fft.fftshift(x)
print(shifted)  # Output: [3 4 1 2]

[3 4 1 2]


* **np.fft.ifftshift(x, axes=None):** The inverse of fftshift.

In [292]:
x = np.array([3, 4, 1, 2])
unshifted = np.fft.ifftshift(x)
print(unshifted)  # Output: [1 2 3 4]

[1 2 3 4]


# **8. NumPy Functions for Data Type Handling**

**I. Data Type Inspection**
* **np.dtype(obj):** Creates a data type object.

In [293]:
dt = np.dtype('int32')
print(dt)  # Output: int32

int32


* **ndarray.dtype:** Returns the data type of an array.

In [294]:
arr = np.array([1, 2, 3])
dtype = arr.dtype
print(dtype)  # Output: int64

int64


* **np.issubdtype(a, b):** Checks if one data type is a subtype of another.

In [295]:
is_subtype = np.issubdtype(np.int32, np.integer)
print(is_subtype)  # Output: True

True


**II. Data Type Conversion**
* **ndarray.astype(dtype):** Casts an array to a specified data type.

In [296]:
arr = np.array([1.1, 2.2, 3.3])
int_arr = arr.astype(int)
print(int_arr)  # Output: [1 2 3]

[1 2 3]


* **np.array(obj, dtype=None):** Creates an array with a specified data type.

In [297]:
arr = np.array([1, 2, 3], dtype=float)
print(arr)  # Output: [1. 2. 3.]

[1. 2. 3.]


* **np.castdtype:** Casts an array to a specified data type.

In [298]:
arr = np.array([1, 2, 3])
float_arr = np.cast[float](arr)
print(float_arr)  # Output: [1. 2. 3.]

[1. 2. 3.]


**III. Data Type Information**
* **np.sctypeDict:** Dictionary mapping dtype chars to scalar types.

In [299]:
print(np.sctypeDict)

{'?': <class 'numpy.bool_'>, 0: <class 'numpy.bool_'>, 'byte': <class 'numpy.int8'>, 'b': <class 'numpy.int8'>, 1: <class 'numpy.int8'>, 'ubyte': <class 'numpy.uint8'>, 'B': <class 'numpy.uint8'>, 2: <class 'numpy.uint8'>, 'short': <class 'numpy.int16'>, 'h': <class 'numpy.int16'>, 3: <class 'numpy.int16'>, 'ushort': <class 'numpy.uint16'>, 'H': <class 'numpy.uint16'>, 4: <class 'numpy.uint16'>, 'i': <class 'numpy.int32'>, 5: <class 'numpy.int32'>, 'uint': <class 'numpy.uint64'>, 'I': <class 'numpy.uint32'>, 6: <class 'numpy.uint32'>, 'intp': <class 'numpy.int64'>, 'p': <class 'numpy.int64'>, 7: <class 'numpy.int64'>, 'uintp': <class 'numpy.uint64'>, 'P': <class 'numpy.uint64'>, 8: <class 'numpy.uint64'>, 'long': <class 'numpy.int64'>, 'l': <class 'numpy.int64'>, 'ulong': <class 'numpy.uint64'>, 'L': <class 'numpy.uint64'>, 'longlong': <class 'numpy.longlong'>, 'q': <class 'numpy.longlong'>, 9: <class 'numpy.longlong'>, 'ulonglong': <class 'numpy.ulonglong'>, 'Q': <class 'numpy.ulonglo

* **np.typeDict:** Dictionary mapping dtype chars to type names.

In [300]:

import numpy as np

# print(np.typeDict)

* **np.find_common_type(arrays):** Finds a common data type for multiple arrays.

In [301]:
import numpy as np

common_type = np.find_common_type([np.int32, np.float64], scalar_types=[]) # Pass dtype objects instead of arrays
print(common_type)  # Output: float64

float64


<ipython-input-301-54ae9ca2be35>:3: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  common_type = np.find_common_type([np.int32, np.float64], scalar_types=[]) # Pass dtype objects instead of arrays


# **9. NumPy Functions for Padding and Trimming**

**I. Padding**

**np.pad(array, pad_width, mode='constant', kwargs):** Adds padding to the edges of an array.

* `pad_width:` Specifies the number of values to pad on each side of the array.
* `mode:` Determines the padding method (e.g., 'constant', 'edge', 'reflect', 'symmetric').
* `kwargs:` Additional arguments for specific padding modes.

In [302]:
arr = np.array([[1, 2], [3, 4]])
padded = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(padded)
# Output:
# [[0 0 0 0]
#  [0 1 2 0]
#  [0 3 4 0]
#  [0 0 0 0]]

[[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 0 0 0]]


**II. Trimming**
**np.trim_zeros(arr, trim='fb'):** Removes leading and/or trailing zeros from an array.

* `trim:` Specifies which edges to trim ('f' for front, 'b' for back).

In [303]:
arr = np.array([0, 0, 1, 2, 0, 0])
trimmed = np.trim_zeros(arr, trim='fb')
print(trimmed)  # Output: [1 2]

[1 2]


# **10. NumPy Functions for Polynomial Operations**

**I. Core Polynomial Functions**
* **np.poly1d(coeffs):** Creates a polynomial object from a list of coefficients.

In [304]:
p = np.poly1d([1, 2, 3])
print(p)  # Output: 1 x^2 + 2 x + 3

   2
1 x + 2 x + 3


* **np.polyval(p, x):** Evaluates a polynomial at specified values.

In [305]:
p = np.poly1d([1, 2, 3])
value = np.polyval(p, 2)
print(value)  # Output: 11

11


* **np.polyfit(x, y, deg, rcond=None, full=False, w=None, cov=False):** Fits a polynomial to data, returning the coefficients.

In [306]:
x = np.array([1, 2, 3, 4])
y = np.array([1, 4, 9, 16])
coeffs = np.polyfit(x, y, 2)
print(coeffs)  # Output: [ 1.00000000e+00 -1.06581410e-14 -7.99360578e-15]

[ 1.00000000e+00 -6.00566855e-15  9.41435428e-15]


* **np.polyder(p, m=1):** Computes the derivative of a polynomial.

In [307]:
p = np.poly1d([1, 2, 3])
derivative = np.polyder(p)
print(derivative)  # Output: 2 x + 2

 
2 x + 2


* **np.polyint(p, m=1, k=0):** Computes the integral of a polynomial.

In [308]:
p = np.poly1d([1, 2, 3])
integral = np.polyint(p)
print(integral)  # Output: 0.33333333 x^3 + x^2 + 3 x

        3     2
0.3333 x + 1 x + 3 x


* **np.roots(p):** Finds the roots of a polynomial.

In [309]:
p = np.poly1d([1, 0, -1])
roots = np.roots(p)
print(roots)  # Output: [ 1. -1.]

[-1.  1.]


**II. Additional Functions**
* **np.polyadd(p1, p2):** Adds two polynomials.

In [310]:
p1 = np.poly1d([1, 2])
p2 = np.poly1d([3, 4])
added = np.polyadd(p1, p2)
print(added)  # Output: 1 x + 5

 
4 x + 6


* **np.polysub(p1, p2):** Subtracts one polynomial from another.

In [311]:
p1 = np.poly1d([1, 2])
p2 = np.poly1d([3, 4])
subtracted = np.polysub(p1, p2)
print(subtracted)  # Output: -2 x - 2

 
-2 x - 2


* **np.polymul(p1, p2):** Multiplies two polynomials.

In [312]:
p1 = np.poly1d([1, 2])
p2 = np.poly1d([3, 4])
multiplied = np.polymul(p1, p2)
print(multiplied)  # Output: 3 x^2 + 10 x + 8

   2
3 x + 10 x + 8


* **np.polydiv(p1, p2):** Divides two polynomials.

In [313]:
p1 = np.poly1d([1, 2])
p2 = np.poly1d([3, 4])
quotient, remainder = np.polydiv(p1, p2)
print(quotient)  # Output: 0.33333333
print(remainder)  # Output: 0.66666667

 
0.3333
 
0.6667


# **11. NumPy Functions for Interpolation and Extrapolation**

**I. np.interp(x, xp, fp, left=None, right=None, period=None): Performs one-dimensional linear interpolation.**

* `x:` Points at which to interpolate.
* `xp:` x-coordinates of the data points.
* `fp:` y-coordinates of the data points.
* `left, right:` Values to return for extrapolation.
* `period:` Period of the data for periodic interpolation.

In [314]:
xp = np.array([0, 1, 2])
fp = np.array([0, 2, 4])
x = np.array([0.5, 1.5])
interp = np.interp(x, xp, fp)
print(interp)  # Output: [1. 3.]

[1. 3.]


**II. np.polyfit(x, y, deg, rcond=None, full=False, w=None, cov=False):** Fits a polynomial to data, returning the coefficients.

In [315]:
x = np.array([0, 1, 2])
y = np.array([0, 1, 4])
coeffs = np.polyfit(x, y, 2)
print(coeffs)  # Output: [ 1.  0. -0.]

[ 1.00000000e+00 -5.53155992e-16  8.39113006e-17]


# **12. NumPy Functions for Financial Operations**

**NumPy-Financial: This library offers functions like npf.fv, npf.pv, npf.rate, npf.pmt, etc., which are similar to Excel's financial functions.**

In [317]:
!pip install numpy_financial
import numpy_financial as npf

# Future value
fv = npf.fv(rate=0.05, nper=10, pmt=-1000, pv=-10000)
print(fv)  # Output: 16288.946267774414

# Present value
pv = npf.pv(rate=0.05, nper=10, pmt=-1000, fv=0)
print(pv)  # Output: 7721.734929184397

# Rate
rate = npf.rate(nper=10, pmt=-1000, pv=-10000, fv=16288.946267774414)
print(rate)  # Output: 0.0500000000000001

# Payment
pmt = npf.pmt(rate=0.05, nper=10, pv=-10000, fv=0)
print(pmt)  # Output: -1295.0242018389665

28866.83880332326
7721.734929184817
-0.028589869900990224
1295.0457496545662


# **13. NumPy Functions Useful for Signal Processing**

**I. np.convolve: Computes the discrete convolution of two one-dimensional sequences.**

In [318]:
a = np.array([1, 2, 3])
v = np.array([0, 1, 0.5])
convolved = np.convolve(a, v, mode='full')
print(convolved)  # Output: [0.  1.  2.5 4.  1.5]

[0.  1.  2.5 4.  1.5]


**II. np.correlate: Computes the correlation of two one-dimensional sequences.**

In [319]:
a = np.array([1, 2, 3])
v = np.array([0, 1, 0.5])
correlated = np.correlate(a, v, mode='full')
print(correlated)  # Output: [0.5 2.  2.5 1. ]

[0.5 2.  3.5 3.  0. ]


# **14. Sharing Memories**

* **np.shares_memory():** Returns True if two arrays share memory.

In [320]:
a = np.array([1, 2, 3])
b = a[:2]
shares_memory = np.shares_memory(a, b)
print(shares_memory)  # Output: True

True


* **np.may_share_memory():** Returns True if two arrays may share memory.

In [321]:
a = np.array([1, 2, 3])
b = a[:2]
may_share_memory = np.may_share_memory(a, b)
print(may_share_memory)  # Output: True

True
