In [11]:
import numpy as np
from scipy.sparse import csr_matrix, lil_matrix, coo_matrix, bsr_matrix, csc_matrix
from scipy.sparse.linalg import eigs, expm

# ================================================================
# 1. Compressed Sparse Row (CSR) Matrix (csr_matrix)
# ================================================================
print("\n1. Compressed Sparse Row (CSR) Matrix:")

# CSR is optimal for row operations and arithmetic
data = np.array([1, 2, 3, 4, 5, 6])
indices = np.array([0, 2, 2, 0, 1, 2])
indptr = np.array([0, 2, 3, 6])  # Row pointers

csr_mat = csr_matrix((data, indices, indptr), shape=(3, 3))

print("CSR Matrix:")
print(csr_mat.toarray())  # Convert to dense for clear visualization
print("\nConclusion: CSR is efficient for row slicing and matrix-vector products. Use Case: Natural Language Processing (TF-IDF matrices)")

# ================================================================
# 2. List of Lists (LIL) Matrix (lil_matrix)
# ================================================================
print("\n2. List of Lists (LIL) Matrix:")

# LIL is best for incremental construction
lil_mat = lil_matrix((3, 3), dtype=int)
lil_mat[0, 0] = 1
lil_mat[0, 2] = 2
lil_mat[1, 2] = 3
lil_mat[2, 0] = 4
lil_mat[2, 1] = 5
lil_mat[2, 2] = 6

print("LIL Matrix:")
print(lil_mat.toarray())
print("\nConclusion: LIL allows flexible construction. Use Case: Incremental matrix building in graph algorithms")

# ================================================================
# 3. Coordinate (COO) Matrix (coo_matrix)
# ================================================================
print("\n3. Coordinate (COO) Matrix:")

# COO is good for fast construction from coordinates
row = np.array([0, 0, 1, 2, 2, 2])
col = np.array([0, 2, 2, 0, 1, 2])
data = np.array([1, 2, 3, 4, 5, 6])

coo_mat = coo_matrix((data, (row, col)), shape=(3, 3))

print("COO Matrix:")
print(coo_mat.toarray())
print("\nConclusion: COO is efficient for conversion from coordinate data. Use Case: Finite element analysis mesh construction")

# ================================================================
# 4. Block Sparse Row (BSR) Matrix (bsr_matrix)
# ================================================================
# print("\n4. Block Sparse Row (BSR) Matrix:")

# # BSR for block-structured matrices
# blocks = np.array([
#     [[1, 2], [3, 4]],  # First block (row 0, col 0)
#     [[5, 6], [7, 8]],  # Second block (row 0, col 1)
#     [[9, 10], [11, 12]],  # Third block (row 1, col 0)
#     [[13, 14], [15, 16]]   # Fourth block (row 1, col 1)
# ])

# indices = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])  # Block row *and column* indices (2D array)

# bsr_mat = bsr_matrix(
#     (blocks, indices), 
#     shape=(4, 4)  # Total size: 2 blocks * 2 rows per block
# )

# print("BSR Matrix (block size 2x2):")
# print(bsr_mat.toarray())
# print("\nConclusion: BSR optimizes block operations. Use Case: Partial differential equations with block-structured grids")

# ================================================================
# 5. Compressed Sparse Column (CSC) Matrix (csc_matrix)
# ================================================================
print("\n5. Compressed Sparse Column (CSC) Matrix:")

# CSC is optimal for column operations
data = np.array([1, 4, 5, 2, 3, 6])
rows = np.array([0, 2, 1, 0, 2, 2])
colptr = np.array([0, 2, 3, 6])

csc_mat = csc_matrix((data, rows, colptr), shape=(3, 3))

print("CSC Matrix:")
print(csc_mat.toarray())
print("\nConclusion: CSC is efficient for column slicing. Use Case: Computer graphics transformations")

# ================================================================
# 6. Sparse Eigenvalues and Eigenvectors (eigs)
# ================================================================
# print("\n6. Sparse Eigenvalues and Eigenvectors:")

# A = csr_matrix([[4, 1], [1, 3]])  # Symmetric matrix for stable eigenvalues
# k = 1  # Find the largest eigenvalue (you can change this)
# eigenvalues, eigenvectors = eigs(A, k=k)  # Get the k largest eigenvalues

# print(f"The {k} largest Eigenvalue(s):", eigenvalues)
# print(f"Corresponding Eigenvector(s):\n", eigenvectors)

# print("\nConclusion: eigs finds a *few* dominant eigenvalues of large sparse matrices efficiently. Use Case: Google PageRank algorithm, PCA on large datasets.")

# # ================================================================
# # 7. Sparse Matrix Exponential (expm)
# # ================================================================
# print("\n7. Sparse Matrix Exponential:")

# A = csr_matrix([[0, 1], [-1, 0]])  # Skew-symmetric matrix
# B = expm(A)  # Should produce rotation matrix

# print("Matrix Exponential:")
# print(B.toarray())
# print("\nConclusion: expm solves matrix ODEs. Use Case: Quantum mechanics time evolution")


1. Compressed Sparse Row (CSR) Matrix:
CSR Matrix:
[[1 0 2]
 [0 0 3]
 [4 5 6]]

Conclusion: CSR is efficient for row slicing and matrix-vector products. Use Case: Natural Language Processing (TF-IDF matrices)

2. List of Lists (LIL) Matrix:
LIL Matrix:
[[1 0 2]
 [0 0 3]
 [4 5 6]]

Conclusion: LIL allows flexible construction. Use Case: Incremental matrix building in graph algorithms

3. Coordinate (COO) Matrix:
COO Matrix:
[[1 0 2]
 [0 0 3]
 [4 5 6]]

Conclusion: COO is efficient for conversion from coordinate data. Use Case: Finite element analysis mesh construction

5. Compressed Sparse Column (CSC) Matrix:
CSC Matrix:
[[1 0 2]
 [0 5 0]
 [4 0 9]]

Conclusion: CSC is efficient for column slicing. Use Case: Computer graphics transformations
