# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
np.__version__

'2.2.4'

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [5]:
np.shares_memory

<function shares_memory at 0x10c6401f0>

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [8]:
import sys
arr=np.arange(100)
print(f"Array {arr}")
print(f"Memory size of array: {sys.getsizeof(arr)} bytes")
print(f"Memory size of an element: {sys.getsizeof(arr[0])} bytes")

Array [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Memory size of array: 912 bytes
Memory size of an element: 32 bytes


#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [9]:
arr=np.zeros(10)
arr[4]=1
print(f"Array {arr}")

Array [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [11]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [13]:
arr=np.arange(10,20)
print(f"Original Array {arr}")
print(f"Reversed Array {arr[::-1]}")

Original Array [10 11 12 13 14 15 16 17 18 19]
Reversed Array [19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [16]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [21]:
arr= [1,2,0,0,4,0]
np.nonzero(arr)[0]

array([0, 1, 4])

#### 11. Create a 3x3 identity matrix (★☆☆)

In [23]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [25]:
np.random.rand(3,3,3)

array([[[0.52556486, 0.82090556, 0.63126068],
        [0.09203192, 0.57972278, 0.32943106],
        [0.38696082, 0.84038378, 0.63694796]],

       [[0.29038072, 0.87599424, 0.77420692],
        [0.25066595, 0.70793357, 0.77394275],
        [0.45289009, 0.46084474, 0.56128393]],

       [[0.63820949, 0.63523497, 0.48052324],
        [0.7925075 , 0.59144907, 0.85408911],
        [0.20312752, 0.5276717 , 0.84449058]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [27]:
arr= np.random.rand(10,10)
print(f"Original Array {arr}")
print(f"Minimum Element of Array {arr.min()}")
print(f"Maximum Element of Array {arr.max()}")

Original Array [[0.66318866 0.32940432 0.61122722 0.03171357 0.95247435 0.34329169
  0.25293678 0.65518604 0.36115476 0.68945426]
 [0.49099414 0.62585772 0.54858947 0.0536653  0.55510598 0.42494617
  0.53413956 0.47909149 0.3401701  0.66753558]
 [0.14763465 0.44829012 0.88164486 0.49534972 0.11808855 0.48667111
  0.75181017 0.50947572 0.0277214  0.54195542]
 [0.86750326 0.09166945 0.44024414 0.27642911 0.81839082 0.72465556
  0.28671596 0.94387013 0.57776456 0.77366011]
 [0.23328538 0.98756693 0.23162453 0.11200281 0.63040983 0.02037011
  0.53331459 0.55869963 0.76122749 0.69169558]
 [0.93001097 0.00398211 0.87484566 0.88023095 0.9336978  0.90883136
  0.50581666 0.62810308 0.66029022 0.33238301]
 [0.34357814 0.0479561  0.28421261 0.98084335 0.38182728 0.66221398
  0.28328544 0.83631379 0.40054133 0.24581625]
 [0.46611757 0.95813346 0.26748536 0.04494931 0.5304212  0.05789004
  0.43573628 0.44836364 0.89302386 0.62324052]
 [0.10351042 0.86613072 0.96058462 0.28259908 0.50386978 0.771099

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
arr= np.random.rand(30)
print(f"Original Array {arr}")
print(f"Mean Value of Array {arr.mean()}")

Original Array [0.11748468 0.12057739 0.06161468 0.64260074 0.10236371 0.4615219
 0.10099837 0.42073699 0.70857331 0.46712051 0.5795374  0.2348997
 0.41662031 0.23480379 0.1580956  0.13504778 0.43551356 0.11526494
 0.37152685 0.42411268 0.79047152 0.71241374 0.95548407 0.17678521
 0.3012728  0.9214688  0.5821741  0.29341273 0.10819273 0.17531187]
Mean Value of Array 0.3775334160658297


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [37]:
arr = np.ones((5, 5))
print(arr)
arr[1:-1, 1:-1] = 0

print("\n\n")
print(f"Original Array {arr}")


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]



Original Array [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [40]:
arr = np.ones((5, 5))
print(arr)

arr[1:-1, 1:-1] = 0

print("\n\n")

# Add a border of zeros around the array
padded_array = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
padded_array


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]





array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [41]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [52]:
np.diag([1,2,3,4], k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [55]:
np.random.rand(8,8)

array([[0.41499465, 0.53340554, 0.25457678, 0.20864782, 0.40679914,
        0.44073244, 0.05958315, 0.40558111],
       [0.10718702, 0.31576062, 0.90461056, 0.916033  , 0.5323032 ,
        0.68548617, 0.76453331, 0.49687726],
       [0.53941662, 0.14647508, 0.98163988, 0.72893096, 0.51985206,
        0.39336323, 0.89639485, 0.28262349],
       [0.59204715, 0.96907686, 0.46418735, 0.76158454, 0.34919937,
        0.85439698, 0.34220891, 0.73753331],
       [0.68435806, 0.85223893, 0.20749513, 0.30448808, 0.4342653 ,
        0.36192702, 0.91905369, 0.01052674],
       [0.62028476, 0.64777123, 0.52980801, 0.14246755, 0.10341362,
        0.56392782, 0.32639496, 0.07997655],
       [0.19902855, 0.41894624, 0.42174969, 0.17741062, 0.11171049,
        0.98531217, 0.84179608, 0.38482803],
       [0.46771265, 0.69387249, 0.42606985, 0.9497722 , 0.06475551,
        0.05755359, 0.32785132, 0.63863331]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
# Shape of the array
shape = (6, 7, 8)

# Find the index of the 100th element (flat index 99)
index = np.unravel_index(99, shape)

print(index)

(np.int64(1), np.int64(5), np.int64(3))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [58]:
# Define a 2x2 checkerboard unit
checker_unit = np.array([[0, 1], [1, 0]])

# Tile the 2x2 unit to create an 8x8 matrix
matrix = np.tile(checker_unit, (4, 4))

print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [59]:
# Create a 5x5 random matrix
matrix = np.random.rand(5, 5)

# Perform min-max normalization
matrix_min = matrix.min()
matrix_max = matrix.max()
normalized_matrix = (matrix - matrix_min) / (matrix_max - matrix_min)

print("Original Matrix:")
print(matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)

Original Matrix:
[[0.35951526 0.30018834 0.53666159 0.00723856 0.90095726]
 [0.78624022 0.23532755 0.38008407 0.76708344 0.46043408]
 [0.26079661 0.92107739 0.07776822 0.93154803 0.43717995]
 [0.38327698 0.29213034 0.48217818 0.1887068  0.03541704]
 [0.13540473 0.34802943 0.8159265  0.81050179 0.44232647]]

Normalized Matrix:
[[0.38112419 0.31693907 0.57277681 0.         0.9669042 ]
 [0.84279312 0.2467669  0.40337735 0.82206761 0.49030712]
 [0.2743216  0.98867193 0.07630524 1.         0.46514874]
 [0.40683173 0.30822121 0.51383182 0.19632844 0.03048597]
 [0.13866153 0.3686978  0.87491037 0.86904144 0.4707167 ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [60]:
mat1=np.random.rand(5,3)
mat2=np.random.rand(3,2)
mat1.dot(mat2)

array([[0.140671  , 0.18043858],
       [0.58640391, 0.77840942],
       [0.56912804, 1.00359698],
       [0.94143747, 0.72416993],
       [0.66762264, 0.74336036]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [62]:
arr = np.array([1, 5, 2, 9, 7, 3, 6, 8, 4, 0, 10])
# Create a boolean mask: True for elements > 3 AND < 8
condition = (arr > 3) & (arr < 8)

# Apply the negation to elements that satisfy the condition
arr[condition] *= -1
arr

array([ 1, -5,  2,  9, -7,  3, -6,  8, -4,  0, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [63]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

In [67]:
arr= np.zeros(10,dtype=np.float16)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float16)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

'm'

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [80]:
a=lambda a1,a2:a1+a2
a(10,29)

39

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)