### ShapeIterationSearch

In [1]:
import numpy as np

# NumPy Array Shape

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print("Shape of arr:\n", arr.shape)  # Returns a tuple (rows, columns)
# Output: Shape of arr:
# (2, 4)
print("\n\n")

print("Number of dimensions (rank):\n", arr.ndim) # Number of dimensions
# Output: Number of dimensions (rank):
# 2
print("\n\n")

print("Size of the array:\n", arr.size) # Total number of elements
# Output: Size of the array:
# 8
print("\n\n")

print("Data type of array elements:\n", arr.dtype) # Data type of elements
# Output: Data type of array elements:
# int64
print("\n\n")


# NumPy Array Iterating

arr = np.array([[1, 2, 3], [4, 5, 6]])

# Iterating 1D arrays:
arr1d = np.array([1,2,3,4,5])

print("Iterating 1D array:")
for x in arr1d:
  print(x)
# Output: Iterating 1D array:
# 1
# 2
# 3
# 4
# 5
print("\n\n")


print("Iterating 2D array (element-wise):")
for x in arr:
  for y in x:
    print(y)
# Output: Iterating 2D array (element-wise):
# 1
# 2
# 3
# 4
# 5
# 6
print("\n\n")

print("Iterating 2D array (row-wise):")
for x in arr:
  print(x)
# Output: Iterating 2D array (row-wise):
# [1 2 3]
# [4 5 6]
print("\n\n")

print("Iterating with nditer (for more control):")
for x in np.nditer(arr):  # nditer handles different array dimensions and order efficiently
    print(x)
# Output: Iterating with nditer (for more control):
# 1
# 2
# 3
# 4
# 5
# 6
print("\n\n")

print("Iterating with ndenumerate (with index):")
for idx, x in np.ndenumerate(arr):
  print(idx, x)
# Output: Iterating with ndenumerate (with index):
# (0, 0) 1
# (0, 1) 2
# (0, 2) 3
# (1, 0) 4
# (1, 1) 5
# (1, 2) 6
print("\n\n")


# NumPy Searching Arrays

arr = np.array([1, 2, 3, 4, 5, 4, 4])

print("np.where(arr == 4):\n", np.where(arr == 4))  # Returns indices where the condition is True
# Output: np.where(arr == 4):
# (array([3, 5, 6]),)
print("\n\n")

print("np.searchsorted(arr, 3):", np.searchsorted(arr, 3)) # For sorted arrays, finds index to insert while maintaining order.
# Output: np.searchsorted(arr, 3): 3
print("\n\n")


# NumPy Filter Array

arr = np.array([1, 2, 3, 4, 5, 6])

# Using boolean indexing (recommended):
filter_arr = arr[arr > 3]  # Creates a new array with elements > 3

print("Filtered array (using boolean indexing):\n", filter_arr)
# Output: Filtered array (using boolean indexing):
# [4 5 6]
print("\n\n")

# Another way using np.where:
indices = np.where(arr > 3)
filter_arr_where = arr[indices]

print("Filtered array (using np.where):\n", filter_arr_where)
# Output: Filtered array (using np.where):
# [4 5 6]
print("\n\n")

Shape of arr:
 (2, 4)



Number of dimensions (rank):
 2



Size of the array:
 8



Data type of array elements:
 int64



Iterating 1D array:
1
2
3
4
5



Iterating 2D array (element-wise):
1
2
3
4
5
6



Iterating 2D array (row-wise):
[1 2 3]
[4 5 6]



Iterating with nditer (for more control):
1
2
3
4
5
6



Iterating with ndenumerate (with index):
(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6



np.where(arr == 4):
 (array([3, 5, 6]),)



np.searchsorted(arr, 3): 2



Filtered array (using boolean indexing):
 [4 5 6]



Filtered array (using np.where):
 [4 5 6]



