### Matrix

In [1]:
import numpy as np

# NumPy - Linear Algebra

# 1. Matrix Library (Creating Matrices)

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
vector = np.array([2, 3])

print("Matrix 1:\n", matrix1)
# Output: Matrix 1:
# [[1 2]
#  [3 4]]
print("\n\n")

print("Matrix 2:\n", matrix2)
# Output: Matrix 2:
# [[5 6]
#  [7 8]]
print("\n\n")

print("Vector:\n", vector)
# Output: Vector:
# [2 3]
print("\n\n")


# 2. Matrix Addition

print("Matrix Addition:\n", matrix1 + matrix2)
# Output: Matrix Addition:
# [[ 6  8]
#  [10 12]]
print("\n\n")

# 3. Matrix Subtraction

print("Matrix Subtraction:\n", matrix1 - matrix2)
# Output: Matrix Subtraction:
# [[-4 -4]
#  [-4 -4]]
print("\n\n")

# 4. Matrix Multiplication (Element-wise)

print("Element-wise Multiplication:\n", matrix1 * matrix2)
# Output: Element-wise Multiplication:
# [[ 5 12]
#  [21 32]]
print("\n\n")

# 5. Dot Product (Matrix Multiplication)

print("Dot Product (Matrix Multiplication):\n", matrix1 @ matrix2)  # or np.dot(matrix1, matrix2)
# Output: Dot Product (Matrix Multiplication):
# [[19 22]
#  [43 50]]
print("\n\n")

print("Dot Product (Matrix-Vector):\n", matrix1 @ vector) # or np.dot(matrix1, vector)
# Output: Dot Product (Matrix-Vector):
# [ 8 14]
print("\n\n")

# 6. Matrix Inversion

matrix_inv = np.linalg.inv(matrix1)
print("Matrix Inverse:\n", matrix_inv)
# Output: Matrix Inverse:
# [[-2.  1. ]
#  [ 1.5 -0.5]]
print("\n\n")

# 7. Determinant Calculation

determinant = np.linalg.det(matrix1)
print("Determinant:\n", determinant)
# Output: Determinant:
# -2.0
print("\n\n")

# 8. Eigenvalues

eigenvalues = np.linalg.eigvals(matrix1)
print("Eigenvalues:\n", eigenvalues)
# Output: Eigenvalues:
# [-0.37228132  5.37228132]
print("\n\n")

# 9. Eigenvectors

eigenvalues, eigenvectors = np.linalg.eig(matrix1)  # Returns both eigenvalues and eigenvectors
print("Eigenvalues:\n", eigenvalues)
# Output: Eigenvalues:
# [-0.37228132  5.37228132]
print("\n\n")
print("Eigenvectors:\n", eigenvectors)
# Output: Eigenvectors:
# [[-0.82456484 -0.41597356]
#  [ 0.56576746 -0.90937671]]
print("\n\n")


# 10. Singular Value Decomposition (SVD)

U, S, V = np.linalg.svd(matrix1) # matrix1 = U * np.diag(S) * V
print("U:\n", U)
print("\n\n")
print("S:\n", S)
print("\n\n")
print("V:\n", V)
print("\n\n")


# 11. Solving Linear Equations

A = np.array([[2, 1], [1, 1]])  # Coefficient matrix
b = np.array([5, 3])  # Constant vector

x = np.linalg.solve(A, b)  # Solve for x in Ax = b
print("Solution to linear equations:\n", x)
# Output: Solution to linear equations:
# [2. 1.]
print("\n\n")

# 12. Matrix Norms

print("Frobenius Norm:\n", np.linalg.norm(matrix1, 'fro'))
# Output: Frobenius Norm:
# 5.477225575051661
print("\n\n")

print("L1 Norm:\n", np.linalg.norm(matrix1, 1))
# Output: L1 Norm:
# 7.0
print("\n\n")

print("L2 Norm:\n", np.linalg.norm(matrix1, 2)) # Largest singular value
# Output: L2 Norm:
# 5.372281323290143
print("\n\n")

print("Infinity Norm:\n", np.linalg.norm(matrix1, np.inf))
# Output: Infinity Norm:
# 7.0
print("\n\n")

Matrix 1:
 [[1 2]
 [3 4]]



Matrix 2:
 [[5 6]
 [7 8]]



Vector:
 [2 3]



Matrix Addition:
 [[ 6  8]
 [10 12]]



Matrix Subtraction:
 [[-4 -4]
 [-4 -4]]



Element-wise Multiplication:
 [[ 5 12]
 [21 32]]



Dot Product (Matrix Multiplication):
 [[19 22]
 [43 50]]



Dot Product (Matrix-Vector):
 [ 8 18]



Matrix Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]



Determinant:
 -2.0000000000000004



Eigenvalues:
 [-0.37228132  5.37228132]



Eigenvalues:
 [-0.37228132  5.37228132]



Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]



U:
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]



S:
 [5.4649857  0.36596619]



V:
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]



Solution to linear equations:
 [2. 1.]



Frobenius Norm:
 5.477225575051661



L1 Norm:
 6.0



L2 Norm:
 5.464985704219043



Infinity Norm:
 7.0



