### Bitwise

In [1]:
import numpy as np

# NumPy Bitwise Operators

# Create some sample arrays
arr1 = np.array([10, 4, 13, 25])  # Example: 1010, 0100, 1101, 11001 in binary
arr2 = np.array([17, 2, 7, 9])   # Example: 10001, 0010, 0111, 1001 in binary

print("Array 1:\n", arr1)
# Output: Array 1:
# [10  4 13 25]
print("\n\n")

print("Array 2:\n", arr2)
# Output: Array 2:
# [17  2  7  9]
print("\n\n")

# 1. Bitwise AND (&)

print("Bitwise AND:\n", np.bitwise_and(arr1, arr2))  # or arr1 & arr2
# Output: Bitwise AND:
# [ 0  0  5  9]  (e.g., 1010 & 10001 = 00000 = 0, 0100 & 0010 = 0000 = 0, etc.)
print("\n\n")

# 2. Bitwise OR (|)

print("Bitwise OR:\n", np.bitwise_or(arr1, arr2))  # or arr1 | arr2
# Output: Bitwise OR:
# [27  6 15 25] (e.g., 1010 | 10001 = 11011 = 27, 0100 | 0010 = 0110 = 6, etc.)
print("\n\n")

# 3. Bitwise XOR (^)

print("Bitwise XOR:\n", np.bitwise_xor(arr1, arr2))  # or arr1 ^ arr2
# Output: Bitwise XOR:
# [27  6 10 16] (e.g., 1010 ^ 10001 = 11011 = 27, 0100 ^ 0010 = 0110 = 6, etc.)
print("\n\n")

# 4. Bitwise NOT (~)

print("Bitwise NOT (arr1):\n", np.bitwise_not(arr1))  # or ~arr1
# Output: Bitwise NOT (arr1):
# [-11  -5 -14 -26] (Two's complement)
print("\n\n")

print("Bitwise NOT (arr2):\n", np.bitwise_not(arr2))  # or ~arr2
# Output: Bitwise NOT (arr2):
# [-18  -3  -8 -10] (Two's complement)
print("\n\n")

# 5. Left Shift (<<)

print("Left Shift (arr1 << 2):\n", np.left_shift(arr1, 2))  # or arr1 << 2  (Shifts bits to the left)
# Output: Left Shift (arr1 << 2):
# [40  16  52 100] (e.g., 1010 << 2 = 101000 = 40, 0100 << 2 = 010000 = 16, etc.)
print("\n\n")

# 6. Right Shift (>>)

print("Right Shift (arr1 >> 1):\n", np.right_shift(arr1, 1))  # or arr1 >> 1 (Shifts bits to the right)
# Output: Right Shift (arr1 >> 1):
# [5 2 6 12] (e.g., 1010 >> 1 = 0101 = 5, 0100 >> 1 = 0010 = 2, etc.)
print("\n\n")

# Example combining operations:

result = (arr1 & arr2) | (arr1 ^ arr2) # This is equivalent to arr1 | arr2
print("Combined Operation:\n", result)
# Output: Combined Operation:
# [27  6 15 25]
print("\n\n")


# Important Note on Bitwise NOT:

# The bitwise NOT operator (~) in NumPy follows two's complement representation.
# This means that the result of ~x is -(x+1).  This is why you see negative
# numbers in the output of the bitwise NOT examples.  It's how negative numbers
# are represented at the bit level.

# Example with a specific bit pattern to illustrate:
num = np.uint8(5) # Use unsigned 8-bit integer to see the bit pattern directly
print("Number (uint8):\n", bin(num))
# Output: Number (uint8):
# 0b101
print("\n\n")

not_num = np.bitwise_not(num)
print("Bitwise NOT (uint8):\n", bin(not_num))
# Output: Bitwise NOT (uint8):
# 0b1111101  (In binary, all bits are flipped)
print("\n\n")

print("Bitwise NOT (decimal):\n", not_num)
# Output: Bitwise NOT (decimal):
# 250 (Which is the two's complement representation of -6 if it was a signed integer)
print("\n\n")

Array 1:
 [10  4 13 25]



Array 2:
 [17  2  7  9]



Bitwise AND:
 [0 0 5 9]



Bitwise OR:
 [27  6 15 25]



Bitwise XOR:
 [27  6 10 16]



Bitwise NOT (arr1):
 [-11  -5 -14 -26]



Bitwise NOT (arr2):
 [-18  -3  -8 -10]



Left Shift (arr1 << 2):
 [ 40  16  52 100]



Right Shift (arr1 >> 1):
 [ 5  2  6 12]



Combined Operation:
 [27  6 15 25]



Number (uint8):
 0b101



Bitwise NOT (uint8):
 0b11111010



Bitwise NOT (decimal):
 250



