### Array Creation


In [1]:
import numpy as np

# 1. Creating NumPy arrays using predefined values

# Creating an array from a list (The list can contain integers, floats, etc.)
arr1 = np.array([1, 2, 3])  

# Creating an array from a tuple (A tuple can also contain any data types)
arr2 = np.array((1, 2, 3))  

# Creating an array from a string (Note: This will create a 1D array with a single string element)
arr3 = np.array(["1,2,4"])  

# Creating an array from a set (Note: Sets are unordered, so NumPy may not handle this as expected)
arr4 = np.array(list({1, 2, 3}))  # Convert set to list before creating array to avoid unexpected behavior

# 2. Additional ways to create arrays with more specific types or values
arr5 = np.array([1, 2, 3], dtype=float)  # Specifying a data type (float)
arr6 = np.array([1, 2, 3], dtype=complex)  # Specifying a complex number data type

# 3. Printing details of each array

print("Array 1 (Created from list):", arr1, "| Data type:", arr1.dtype)
# Output: Array 1 (Created from list): [1 2 3] | Data type: int32 (or int64 depending on system)

print("Array 2 (Created from tuple):", arr2, "| Data type:", arr2.dtype)
# Output: Array 2 (Created from tuple): [1 2 3] | Data type: int32 (or int64)

print("Array 3 (Created from string):", arr3, "| Data type:", arr3.dtype)
# Output: Array 3 (Created from string): ['1,2,4'] | Data type: <U5 (Unicode string)

print("Array 4 (Created from set, converted to list):", arr4, "| Data type:", arr4.dtype)
# Output (order may vary): Array 4 (Created from set, converted to list): [1 2 3] | Data type: int32 (or int64)

# Additional arrays with explicit data types
print("Array 5 (Created with float type):", arr5, "| Data type:", arr5.dtype)
# Output: Array 5 (Created with float type): [1. 2. 3.] | Data type: float64

print("Array 6 (Created with complex type):", arr6, "| Data type:", arr6.dtype)
# Output: Array 6 (Created with complex type): [1.+0.j 2.+0.j 3.+0.j] | Data type: complex128


Array 1 (Created from list): [1 2 3] | Data type: int64
Array 2 (Created from tuple): [1 2 3] | Data type: int64
Array 3 (Created from string): ['1,2,4'] | Data type: <U5
Array 4 (Created from set, converted to list): [1 2 3] | Data type: int64
Array 5 (Created with float type): [1. 2. 3.] | Data type: float64
Array 6 (Created with complex type): [1.+0.j 2.+0.j 3.+0.j] | Data type: complex128


In [2]:
import numpy as np

# Built-in functions to create arrays with predefined values

# Creating a 2x2 array filled with zeros
zeros_array = np.zeros((2, 2))
print("Array filled with zeros:\n", zeros_array)
# Output:
# [[0. 0.]
#  [0. 0.]]

# Creating a 2x2 array filled with ones
ones_array = np.ones((2, 2))
print("\nArray filled with ones:\n", ones_array)
# Output:
# [[1. 1.]
#  [1. 1.]]

# Creating a 2x2 array filled with a specific value (5)
full_array = np.full((2, 2), 5)
print("\nArray filled with the value 5:\n", full_array)
# Output:
# [[5 5]
#  [5 5]]

# Creating an empty array (size 0) - will return an empty array
empty_array = np.empty((0,))
print("\nEmpty array (size 0):\n", empty_array)
# Output:
# []  (an empty array)

# Creating an identity matrix (2x2) using np.eye()
eye_array = np.eye(2)
print("\nIdentity matrix (2x2) using np.eye():\n", eye_array)
# Output:
# [[1. 0.]
#  [0. 1.]]

# Creating an identity matrix (4x4) using np.identity()
identity_array = np.identity(4)
print("\nIdentity matrix (4x4) using np.identity():\n", identity_array)
# Output:
# [[1. 0. 0. 0.]
#  [0. 1. 0. 0.]
#  [0. 0. 1. 0.]
#  [0. 0. 0. 1.]]

# Creating a diagonal matrix from a given list of values
diag_array = np.diag([1, 2, 3])
print("\nDiagonal matrix from [1, 2, 3]:\n", diag_array)
# Output:
# [[1 0 0]
#  [0 2 0]
#  [0 0 3]]


Array filled with zeros:
 [[0. 0.]
 [0. 0.]]

Array filled with ones:
 [[1. 1.]
 [1. 1.]]

Array filled with the value 5:
 [[5 5]
 [5 5]]

Empty array (size 0):
 []

Identity matrix (2x2) using np.eye():
 [[1. 0.]
 [0. 1.]]

Identity matrix (4x4) using np.identity():
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Diagonal matrix from [1, 2, 3]:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]


In [3]:
import numpy as np

# 1. Creating an array using np.arange() (Sequence with a step)
# Generates numbers from 1 to 19 (excluding 20) with a step of 2
arange_array = np.arange(1, 20, 2)
print("Array created using np.arange(1, 20, 2):", arange_array)
# Output:
# [ 1  3  5  7  9 11 13 15 17 19]

# 2. Creating an array using np.linspace() (Evenly spaced values)
# Generates 5 evenly spaced numbers between 1 and 2
linspace_array = np.linspace(1, 2, 5)
print("\nArray created using np.linspace(1, 2, 5):", linspace_array)
# Output:
# [1.   1.25 1.5  1.75 2.  ]

# 3. Creating an array using np.logspace() (Logarithmically spaced values)
# Generates 10 values between 10^1 and 10^2
logspace_array = np.logspace(1, 2, 10)
print("\nArray created using np.logspace(1, 2, 10):", logspace_array)
# Output:
# [ 10.          12.91549665  16.68100537  21.5443469   27.82559402  
#   35.93813664  46.41588834  59.94842503  77.42636827 100.        ]

# 4. Creating an array using np.geomspace() (Geometrically spaced values)
# Generates 5 values between 1 and 1000, where ratio between consecutive elements is constant
geomspace_array = np.geomspace(1, 1000, 5)
print("\nArray created using np.geomspace(1, 1000, 5):", geomspace_array)
# Output:
# [   1.   10.  100. 1000.]

# 5. Creating an array using np.meshgrid() (Generating coordinate grids)
x = np.array([0, 1, 2])
y = np.array([0, 1, 2])
X, Y = np.meshgrid(x, y)

print("\nMeshgrid X-coordinates:\n", X)
# Output:
# [[0 1 2]
#  [0 1 2]
#  [0 1 2]]

print("\nMeshgrid Y-coordinates:\n", Y)
# Output:
# [[0 0 0]
#  [1 1 1]
#  [2 2 2]]


Array created using np.arange(1, 20, 2): [ 1  3  5  7  9 11 13 15 17 19]

Array created using np.linspace(1, 2, 5): [1.   1.25 1.5  1.75 2.  ]

Array created using np.logspace(1, 2, 10): [ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]

Array created using np.geomspace(1, 1000, 5): [   1.            5.62341325   31.6227766   177.827941   1000.        ]

Meshgrid X-coordinates:
 [[0 1 2]
 [0 1 2]
 [0 1 2]]

Meshgrid Y-coordinates:
 [[0 0 0]
 [1 1 1]
 [2 2 2]]


In [4]:
import numpy as np

# 1. Creating an array of random numbers from a uniform distribution [0, 1)
rand_array = np.random.rand(3, 3)  # 3x3 array with random values from a uniform distribution
print("Random numbers from uniform distribution (rand):\n", rand_array)
# Output: (Values will vary)
# [[0.51790142 0.68296934 0.20433195]
#  [0.13021987 0.14745703 0.18877887]
#  [0.12492998 0.12247012 0.72587519]]

# 2. Creating a 2x2 array from a normal distribution (mean=0, std=1)
randn_array = np.random.randn(2, 2)  # 2x2 array with random numbers from a normal distribution
print("\nRandom numbers from normal distribution (randn):\n", randn_array)
# Output: (Values will vary)
# [[ 0.52202684 -0.12209115]
#  [ 0.36813991 -0.16195084]]

# 3. Creating a 3x3 array with random integers in the range [1, 3)
randint_array = np.random.randint(1, 3, size=(3, 3))  # Random integers between 1 and 3 (exclusive of 3)
print("\nRandom integers between 1 and 3:\n", randint_array)
# Output: (Values will vary)
# [[1 2 1]
#  [1 2 1]
#  [2 1 2]]

# 4. Creating a 10-element array with random floats from the interval [0, 1)
random_array = np.random.random(10)  # Random float values between 0 and 1
print("\nRandom floats between 0 and 1 (random):\n", random_array)
# Output: (Values will vary)
# [0.12213132 0.64235094 0.71007527 0.28946397 0.98646356 0.7687247
#  0.12260493 0.91365848 0.48149349 0.13642649]

# 5. Creating a 10-element array using the old `np.ranf()` (same as np.random.random())
ranf_array = np.random.ranf(10)  # Random floats between 0 and 1, similar to random
print("\nRandom floats between 0 and 1 (ranf):\n", ranf_array)
# Output: (Values will vary)
# [0.34990483 0.44333723 0.58773266 0.58118448 0.69393176 0.58859561
#  0.71067252 0.31490472 0.77791398 0.75924629]

# 6. Creating an array from a normal distribution with mean=0, std=1
normal_array = np.random.normal(size=(1, 3))  # Generates a single array with 3 random values from normal dist
print("\nRandom values from normal distribution (mean=0, std=1):\n", normal_array)
# Output: (Values will vary)
# [[-0.53602771  0.7034647  -0.46774161]]

# 7. Creating a 1D array with random numbers from a uniform distribution [0, 1)
uniform_array = np.random.uniform(size=(1, 3))  # Random floats from a uniform distribution
print("\nRandom values from uniform distribution (0, 1):\n", uniform_array)
# Output: (Values will vary)
# [[0.90737779 0.64925553 0.44492258]]

# 8. Generating random values from a binomial distribution (1 trial, probability 0.5)
binomial_array = np.random.binomial(1, 0.5, size=(1, 3))  # Binomial distribution with n=1, p=0.5
print("\nRandom values from binomial distribution:\n", binomial_array)
# Output: (Values will vary)
# [[1 1 0]]

# 9. Additional: Generating random values from a Poisson distribution (mean=5)
poisson_array = np.random.poisson(5, size=(1, 3))  # Values from Poisson distribution with mean 5
print("\nRandom values from Poisson distribution:\n", poisson_array)
# Output: (Values will vary)
# [[4 7 5]]


Random numbers from uniform distribution (rand):
 [[9.23814086e-01 5.88554943e-01 7.05068937e-01]
 [9.02633732e-01 4.68338298e-04 5.43552377e-01]
 [3.55363019e-01 2.75814504e-01 3.03813347e-01]]

Random numbers from normal distribution (randn):
 [[-0.19703812  0.87208372]
 [-1.0307266  -0.65565108]]

Random integers between 1 and 3:
 [[2 1 2]
 [1 1 2]
 [1 1 1]]

Random floats between 0 and 1 (random):
 [0.76783253 0.61854223 0.0567196  0.06441709 0.19140007 0.97317609
 0.68237005 0.20115263 0.68966088 0.8910926 ]

Random floats between 0 and 1 (ranf):
 [0.22561929 0.92698732 0.43196792 0.66917692 0.37757279 0.65320384
 0.9343488  0.89186064 0.12696125 0.86728156]

Random values from normal distribution (mean=0, std=1):
 [[1.2946165  0.10058657 0.12794671]]

Random values from uniform distribution (0, 1):
 [[0.37073618 0.90305738 0.1629808 ]]

Random values from binomial distribution:
 [[1 1 0]]

Random values from Poisson distribution:
 [[7 5 1]]


In [5]:
import numpy as np

# 1. Changing the shape of an array

# Original 1D array
org_arr = np.array([1, 2, 3, 4, 5, 6])

# Reshaping to 2x3 array
reshaped_arr = np.reshape(org_arr, (2, 3))
print("Reshape -> ", reshaped_arr)
# Output:
# [[1 2 3]
#  [4 5 6]]

# Flattening the reshaped array (converting to 1D)
rvl_arr = np.ravel(reshaped_arr)
print("Ravel -> ", rvl_arr)
# Output: [1 2 3 4 5 6] (flattened to a 1D array)

# Flattening the reshaped array (alternative method)
flt_arr = reshaped_arr.flatten()
print("Flatten -> ", flt_arr)
# Output: [1 2 3 4 5 6] (same result as ravel)

# 2. Transpose of an array

# A 3x2 array
trs = np.array([[1, 2], [3, 4], [5, 6]])

# Transposing the array (converting rows to columns and vice versa)
print("Transpose -> ", np.transpose(trs))
# Output:
# [[1 3 5]
#  [2 4 6]]

# 3. Swapping axes (swap rows and columns)

# A 3x2 array
swp = np.array([[1, 2], [3, 4], [5, 6]])

# Swapping axes (switching the index of rows and columns)
print("SwapAxes -> ", np.swapaxes(swp, 1, 0))
# Output:
# [[1 3 5]
#  [2 4 6]]

# 4. Rolling the axes of an array

# A 3x2 array
roll = np.array([[1, 2], [3, 4], [5, 6]])

# Rolling the axis (moving the second axis to the front)
print("RollAxis -> ", np.rollaxis(roll, 1))
# Output:
# [[1 3 5]
#  [2 4 6]]


Reshape ->  [[1 2 3]
 [4 5 6]]
Ravel ->  [1 2 3 4 5 6]
Flatten ->  [1 2 3 4 5 6]
Transpose ->  [[1 3 5]
 [2 4 6]]
SwapAxes ->  [[1 3 5]
 [2 4 6]]
RollAxis ->  [[1 3 5]
 [2 4 6]]


In [6]:
import numpy as np

# 1. Concatenating two arrays along a specified axis

arr1 = np.array([[1, 2]])
arr2 = np.array([[3, 4]])

# Concatenating arrays along axis 0 (rows)
print("Concatenate (axis=0) -> ", np.concatenate((arr1, arr2), axis=0))
# Output:
# [[1 2]
#  [3 4]]

# 2. Stacking arrays vertically (along axis 0)

print("VStack -> ", np.vstack((arr1, arr2)))
# Output:
# [[1 2]
#  [3 4]]

# 3. Stacking arrays horizontally (along axis 1)

print("HStack -> ", np.hstack((arr1, arr2)))
# Output:
# [[1 2 3 4]]

# 4. Stacking arrays along the third axis (depth)

print("DStack -> ", np.dstack((arr1, arr2)))
# Output:
# [[[1 3]]
#  [[2 4]]]

# 5. Stacking arrays as columns (similar to hstack, but treats arrays as columns)

print("Column_stack -> ", np.column_stack((arr1, arr2)))
# Output:
# [[1 3]
#  [2 4]]


Concatenate (axis=0) ->  [[1 2]
 [3 4]]
VStack ->  [[1 2]
 [3 4]]
HStack ->  [[1 2 3 4]]
DStack ->  [[[1 3]
  [2 4]]]
Column_stack ->  [[1 2 3 4]]


In [7]:
import numpy as np

# 1. Splitting the array into equal parts (if possible)

arr1 = np.array([1, 2, 3, 4, 5, 6])

# Split the array into 3 equal parts
print("Split (equal size parts) -> ", np.split(arr1, 3))
# Output:
# [array([1, 2]), array([3, 4]), array([5, 6])]
# Note: Array will be split into 3 equal parts. If the array size is not divisible by 3, an error will occur.

# 2. Array splitting when the size is not exactly divisible by the number of splits

print("Array Split (handles uneven splits) -> ", np.array_split(arr1, 3))
# Output:
# [array([1, 2]), array([3, 4]), array([5, 6])]
# Note: `np.array_split()` can handle uneven splits and will create an extra smaller array if necessary.

# 3. Horizontal splitting (splits along columns)

print("Hsplit (horizontal split) -> ", np.hsplit(arr1, 3))
# Output:
# [array([1, 2]), array([3, 4]), array([5, 6])]
# Note: Works similarly to split but splits the array along the horizontal axis (columns).

# 4. Vertical splitting (splitting a 2D array into sub-arrays along rows)

arr1 = np.array([[1, 2], [3, 4], [5, 6]])

print("Vsplit (vertical split) -> ", np.vsplit(arr1, 3))
# Output:
# [array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
# Note: `np.vsplit()` splits the 2D array along the vertical axis (rows).


Split (equal size parts) ->  [array([1, 2]), array([3, 4]), array([5, 6])]
Array Split (handles uneven splits) ->  [array([1, 2]), array([3, 4]), array([5, 6])]
Hsplit (horizontal split) ->  [array([1, 2]), array([3, 4]), array([5, 6])]
Vsplit (vertical split) ->  [array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]


In [8]:
# adding and removing the elements 

arr1=np.array([1,2,3,4,5,6])
print("append --> ", np.append(arr1, 7))


print("insert --> ", np.insert(arr1, 0, [0]))

print("delete --> ", np.delete(arr1,[1]))


print("resize --> ", np.resize(arr1,(2,3)))


append -->  [1 2 3 4 5 6 7]
insert -->  [0 1 2 3 4 5 6]
delete -->  [1 3 4 5 6]
resize -->  [[1 2 3]
 [4 5 6]]


In [9]:
import numpy as np

# 1. Copying an array (creating a separate copy to avoid reference issues)

arr1 = np.array([1, 2, 3, 4, 5, 6])

# Making a copy of the original array
copied = arr1.copy()

# Printing the original array and its memory location
print(f"Original array --> {arr1} and its location {id(arr1)}")
# Output: Original array --> [1 2 3 4 5 6] and its location <memory_location>

# Printing the copied array and its memory location
print(f"Array copied --> {copied} and its location {id(copied)}")
# Output: Array copied --> [1 2 3 4 5 6] and its location <new_memory_location>
# Note: The memory locations will be different since `copy()` creates a new object.

# 2. Removing single-dimensional entries from the shape of an array

arr1 = np.array([[1, 2, 3, 4, 5, 6]])

# Using squeeze to remove single-dimensional entries
print(f"Array squeezed --> {np.squeeze(arr1)} and its dimensions {np.squeeze(arr1).shape}")
# Output:
# Array squeezed --> [1 2 3 4 5 6] and its dimensions (6,)
# Note: `np.squeeze()` removes any dimensions with size 1 from the array shape.

# 3. Expanding the dimensions of an array (inserting a new axis)

print(f"Expanded dimensions --> {np.expand_dims(arr1, axis=1)} and its dimensions {np.expand_dims(arr1, axis=1).shape}")
# Output:
# Expanded dimensions --> [[[1 2 3 4 5 6]]] and its dimensions (1, 6, 1)
# Note: `np.expand_dims()` adds a new axis to the array along the specified axis (axis=1 in this case).

# 4. Flipping arrays

arr1 = np.array([[1, 2], [3, 4]])

# Flipping the entire array
print(f"\nOriginal array\n{arr1} and flip\n{np.flip(arr1)}")
# Output:
# Original array
# [[1 2]
#  [3 4]] 
# and flip
# [[4 3]
#  [2 1]]
# Note: `np.flip()` flips all elements in the array.

# Flipping the array left to right (horizontal flip)
print(f"\nOriginal array\n{arr1} and flip (left-right)\n{np.fliplr(arr1)}")
# Output:
# Original array
# [[1 2]
#  [3 4]] 
# and flip (left-right)
# [[2 1]
#  [4 3]]
# Note: `np.fliplr()` flips the array along its horizontal axis (left-right).

# Flipping the array up to down (vertical flip)
print(f"\nOriginal array\n{arr1} and flip (up-down)\n{np.flipud(arr1)}")
# Output:
# Original array
# [[1 2]
#  [3 4]] 
# and flip (up-down)
# [[3 4]
#  [1 2]]
# Note: `np.flipud()` flips the array along its vertical axis (up-down).


Original array --> [1 2 3 4 5 6] and its location 4456847376
Array copied --> [1 2 3 4 5 6] and its location 4456845936
Array squeezed --> [1 2 3 4 5 6] and its dimensions (6,)
Expanded dimensions --> [[[1 2 3 4 5 6]]] and its dimensions (1, 1, 6)

Original array
[[1 2]
 [3 4]] and flip
[[4 3]
 [2 1]]

Original array
[[1 2]
 [3 4]] and flip (left-right)
[[2 1]
 [4 3]]

Original array
[[1 2]
 [3 4]] and flip (up-down)
[[3 4]
 [1 2]]


In [10]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original array:\n", arr)

# Rotate once (90 degrees counter-clockwise)
rotated_once = np.rot90(arr)
print("\nRotated once:\n", rotated_once)

# Rotate twice (180 degrees)
rotated_twice = np.rot90(arr, k=2)
print("\nRotated twice:\n", rotated_twice)

# Rotate three times (270 degrees counter-clockwise or 90 degrees clockwise)
rotated_three = np.rot90(arr, k=3)
print("\nRotated three times:\n", rotated_three)

# Rotate clockwise (90 degrees)
rotated_clockwise = np.rot90(arr, k=-1)
print("\nRotated clockwise:\n", rotated_clockwise)


# Example with higher dimensions and specifying axes

arr_3d = np.arange(24).reshape(2, 3, 4)
print("\nOriginal 3D array:\n", arr_3d)

# Rotate along axes 1 and 2
rotated_3d = np.rot90(arr_3d, k=1, axes=(1, 2))
print("\nRotated 3D array (axes 1 and 2):\n", rotated_3d)

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Rotated once:
 [[3 6 9]
 [2 5 8]
 [1 4 7]]

Rotated twice:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]

Rotated three times:
 [[7 4 1]
 [8 5 2]
 [9 6 3]]

Rotated clockwise:
 [[7 4 1]
 [8 5 2]
 [9 6 3]]

Original 3D array:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Rotated 3D array (axes 1 and 2):
 [[[ 3  7 11]
  [ 2  6 10]
  [ 1  5  9]
  [ 0  4  8]]

 [[15 19 23]
  [14 18 22]
  [13 17 21]
  [12 16 20]]]


In [11]:
import numpy as np

# 1. Indexing an array (accessing a specific element by its index)

arr = np.array([1, 2, 3, 4, 5, 6])

# Accessing the element at index 4 (5th element, zero-indexed)
print(f"Indexing of array: {arr[4]}")
# Output:
# Indexing of array: 5
# Note: Arrays in NumPy are zero-indexed, so `arr[4]` refers to the 5th element (which is 5).

# 2. Slicing an array (getting a sub-array or range of elements)

# Slicing the array from index 2 to 3 (it includes the start index, but not the end index)
print(f"Slicing of array: {arr[2:3]}")
# Output:
# Slicing of array: [3]
# Note: `arr[2:3]` gives a sub-array starting at index 2, ending just before index 3 (i.e., array with only 3).

# 3. Boolean indexing (accessing elements based on a condition)

# Extracting all elements in the array that are greater than 3
print(f"Boolean indexing of array: {arr[arr > 3]}")
# Output:
# Boolean indexing of array: [4 5 6]
# Note: This uses a condition to filter out the values. Only elements greater than 3 (4, 5, 6) are returned.


Indexing of array: 5
Slicing of array: [3]
Boolean indexing of array: [4 5 6]


In [12]:
import numpy as np

arr = np.array([1, 2, 3, 2, 4, 3, 5, 4, 6])
sorted_arr = np.sort(arr)
print(f"original array\n {arr} and sorted \n  {sorted_arr} and its id \n {id(sorted_arr)}")
# Outputs:
# original array
#  [1 2 3 2 4 3 5 4 6] and sorted 
#   [1 2 2 3 3 4 4 5 6] and its id 
#  <id of sorted_arr (different from arr)>

print("\n")

arr.sort()  # Sorts the array IN PLACE
print(f"original array\n {arr} and sorted \n  {arr} and its id \n {id(arr)}")
# Outputs:
# original array
#  [1 2 2 3 3 4 4 5 6] and sorted 
#   [1 2 2 3 3 4 4 5 6] and its id 
#  <id of arr (same as original array's id after in-place sort)>

print("\n")

arr = np.array([1, 2, 3, 2, 4, 3, 5, 4, 6])
argsorted = np.argsort(arr)
print(f"original array\n {arr} and arg sorted \n  {argsorted} and based on arg sort the array {arr[argsorted]} its id \n {id(argsorted)}")
# Outputs:
# original array
#  [1 2 3 2 4 3 5 4 6] and arg sorted 
#   [0 3 1 4 5 7 8 2 6] and based on arg sort the array [1 2 2 3 3 4 4 5 6] its id 
#  <id of argsorted array>

print("\n")

keys = np.array([[1, 0, 3], [0, 2, 2]])
lexsorted_indices = np.lexsort(keys)
print(f"keys array\n {keys} and lex sorted indices \n  {lexsorted_indices} and its id \n {id(lexsorted_indices)}")
# Outputs:
# keys array
#  [[1 0 3]
#  [0 2 2]] and lex sorted indices 
#   [1 0 2] and its id 
#  <id of lexsorted_indices array>

print("\n")

arr = np.array([1, 2, 3, 2, 4, 3, 5, 4, 6])
partitioned = np.partition(arr, 2)
print(f"original array\n {arr} and partitions \n  {partitioned} and its id \n {id(partitioned)}")
# Outputs:
# original array
#  [1 2 3 2 4 3 5 4 6] and partitions 
#   [1 2 2 3 4 3 5 4 6] and its id 
#  <id of partitioned array (new array)>

print("\n")

arr = np.array([1, 2, 3, 2, 4, 3, 5, 4, 6])
argpartitioned = np.argpartition(arr, 2)
print(f"original array\n {arr} and arg partitions \n  {argpartitioned} and its id \n {id(argpartitioned)}")
# Outputs:
# original array
#  [1 2 3 2 4 3 5 4 6] and arg partitions 
#   [0 3 1 2 4 5 7 8 6] and its id 
#  <id of argpartitioned array>

print("\n")

arr = np.array([1, 2, 3, 2, 4, 3, 5, 4, 6])
arr.sort()
print(f"original array (after in-place sort)\n {arr} and sorted \n  {arr} and its id \n {id(arr)}")
# Outputs:
# original array (after in-place sort)
#  [1 2 2 3 3 4 4 5 6] and sorted 
#   [1 2 2 3 3 4 4 5 6] and its id 
#  <id of arr (same as original array's id after in-place sort)>

original array
 [1 2 3 2 4 3 5 4 6] and sorted 
  [1 2 2 3 3 4 4 5 6] and its id 
 4383312944


original array
 [1 2 2 3 3 4 4 5 6] and sorted 
  [1 2 2 3 3 4 4 5 6] and its id 
 4456852624


original array
 [1 2 3 2 4 3 5 4 6] and arg sorted 
  [0 1 3 2 5 4 7 6 8] and based on arg sort the array [1 2 2 3 3 4 4 5 6] its id 
 4383313136


keys array
 [[1 0 3]
 [0 2 2]] and lex sorted indices 
  [0 1 2] and its id 
 4456851472


original array
 [1 2 3 2 4 3 5 4 6] and partitions 
  [1 2 2 3 4 3 5 4 6] and its id 
 4383313040


original array
 [1 2 3 2 4 3 5 4 6] and arg partitions 
  [0 1 3 2 4 5 6 7 8] and its id 
 4456853200


original array (after in-place sort)
 [1 2 2 3 3 4 4 5 6] and sorted 
  [1 2 2 3 3 4 4 5 6] and its id 
 4456852528


In [13]:
import numpy as np

arr = np.array([1, 2, np.nan, 4, 5, 6, np.nan])

print(f"Original array {arr}")  # Output: Original array [ 1.  2. nan  4.  5.  6. nan]
print(f"argmin (without NaN handling): {np.argmin(arr)}")  # Output: argmin (without NaN handling): 2

print("\n")

print(f"Original array {arr}")  # Output: Original array [ 1.  2. nan  4.  5.  6. nan]
print(f"nanargmin (ignores NaNs): {np.nanargmin(arr)}")  # Output: nanargmin (ignores NaNs): 0

print("\n")

print(f"Original array {arr}")  # Output: Original array [ 1.  2. nan  4.  5.  6. nan]
print(f"argmax (without NaN handling): {np.argmax(arr)}")  # Output: argmax (without NaN handling): 2

print("\n")

print(f"Original array {arr}")  # Output: Original array [ 1.  2. nan  4.  5.  6. nan]
print(f"nanargmax (ignores NaNs): {np.nanargmax(arr)}")  # Output: nanargmax (ignores NaNs): 5

print("\n")

print(f"Original array {arr}")  # Output: Original array [ 1.  2. nan  4.  5.  6. nan]
print(f"where clause conditional (arr > 3): {np.where(arr > 3)}")  # Output: where clause conditional (arr > 3): (array([3, 4, 5]),)

print("\n")

#Find the indices of all nan values.
nan_indices = np.where(np.isnan(arr))
print(f"Indices of NaN values: {nan_indices}")  # Output: Indices of NaN values: (array([2, 6]),)

#Find the indices of all non nan values.
non_nan_indices = np.where(~np.isnan(arr))
print(f"Indices of non-NaN values: {non_nan_indices}")  # Output: Indices of non-NaN values: (array([0, 1, 3, 4, 5]),)

#Find the minimum value in the array ignoring nan values.
min_val = np.nanmin(arr)
print(f"Minimum value ignoring NaNs: {min_val}") # Output: Minimum value ignoring NaNs: 1.0

#Find the maximum value in the array ignoring nan values.
max_val = np.nanmax(arr)
print(f"Maximum value ignoring NaNs: {max_val}") # Output: Maximum value ignoring NaNs: 6.0

Original array [ 1.  2. nan  4.  5.  6. nan]
argmin (without NaN handling): 2


Original array [ 1.  2. nan  4.  5.  6. nan]
nanargmin (ignores NaNs): 0


Original array [ 1.  2. nan  4.  5.  6. nan]
argmax (without NaN handling): 2


Original array [ 1.  2. nan  4.  5.  6. nan]
nanargmax (ignores NaNs): 5


Original array [ 1.  2. nan  4.  5.  6. nan]
where clause conditional (arr > 3): (array([3, 4, 5]),)


Indices of NaN values: (array([2, 6]),)
Indices of non-NaN values: (array([0, 1, 3, 4, 5]),)
Minimum value ignoring NaNs: 1.0
Maximum value ignoring NaNs: 6.0


In [14]:
import numpy as np

# 1- Data Type Inspection
arr = np.array([1, 2, 4, 5, 6])
print(f"Original array: {arr}, and its primary data type: {arr.dtype}")
# Output: Original array: [1 2 4 5 6], and its primary data type: int32

print("\n")

# Convert array to int64 and check its type
arr_int64 = arr.astype(np.int64)
print(f"Converted array to int64: {arr_int64}, and its new data type: {arr_int64.dtype}")
# Output: Converted array to int64: [1 2 4 5 6], and its new data type: int64

print("\n")

# Check if np.int32 is a subtype of np.integer
print(f"Is np.int32 a subtype of np.integer? {np.issubdtype(np.int32, np.integer)}")
# Output: Is np.int32 a subtype of np.integer? True

print("\n")

# 2. Data Type Conversion
print(f"Original array: {arr}, converted to float, new data type: {arr.astype(float).dtype}")
# Output: Original array: [1 2 4 5 6], converted to float, new data type: float64

print("\n")

# Creating an array with a specified data type (int)
arr = np.array([1.0, 2.0, 3.0, 4.0], dtype=int)
print(f"Created array with specified dtype=int: {arr}, actual dtype: {arr.dtype}")
# Output: Created array with specified dtype=int: [1 2 3 4], actual dtype: int64

print("\n")

# Casting an array to float using arr.astype
casted_arr = arr.astype(float)
print(f"Casted array to float: {casted_arr}, new data type: {casted_arr.dtype}")
# Output: Casted array to float: [1. 2. 3. 4.], new data type: float64

print("\n")

# 3. Data Type Information
# Displaying only 5 items from np.sctypeDict to avoid long output
print(f"Sample of dictionary mapping dtype chars to scalar types: {list(np.sctypeDict.items())[:5]}")
# Output: Sample of dictionary mapping dtype chars to scalar types: [('?','bool'), ('b','int8'), ('B','uint8'), ('h','int16'), ('H','uint16')]

print("\n")

# Find a common data type for multiple arrays
common_dtype = np.result_type(np.int32, np.float64)
print(f"Common data type for int32 and float64: {common_dtype}")
# Output: Common data type for int32 and float64: float64


Original array: [1 2 4 5 6], and its primary data type: int64


Converted array to int64: [1 2 4 5 6], and its new data type: int64


Is np.int32 a subtype of np.integer? True


Original array: [1 2 4 5 6], converted to float, new data type: float64


Created array with specified dtype=int: [1 2 3 4], actual dtype: int64


Casted array to float: [1. 2. 3. 4.], new data type: float64


Sample of dictionary mapping dtype chars to scalar types: [('bool', <class 'numpy.bool'>), ('float16', <class 'numpy.float16'>), ('float32', <class 'numpy.float32'>), ('float64', <class 'numpy.float64'>), ('longdouble', <class 'numpy.longdouble'>)]


Common data type for int32 and float64: float64


In [15]:
import numpy as np

# 1. Padding
# Original 2x2 array
arr = np.array([[1, 2], 
                [3, 4]])

# Padding with a border of 1 row/column filled with zeros
padded = np.pad(arr, pad_width=1, mode='constant', constant_values=0)

print("Original Array:\n", arr)
# Output:
# [[1 2]
#  [3 4]]

print("\nPadded Array with 1-row/column border of zeros:\n", padded)
# Output:
# [[0 0 0 0]
#  [0 1 2 0]
#  [0 3 4 0]
#  [0 0 0 0]]


# 2. Trimming (Removing Leading and Trailing Zeros)
# Creating a 1D array with leading and trailing zeros
arr = np.array([0, 0, 1, 2, 0, 0])

# Using np.trim_zeros to remove leading ('f') and trailing ('b') zeros
trimmed = np.trim_zeros(arr, trim='fb')

print("\nOriginal Array with Leading & Trailing Zeros:", arr)
# Output: [0 0 1 2 0 0]

print("Trimmed Array (Zeros Removed):", trimmed)
# Output: [1 2]


Original Array:
 [[1 2]
 [3 4]]

Padded Array with 1-row/column border of zeros:
 [[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 0 0 0]]

Original Array with Leading & Trailing Zeros: [0 0 1 2 0 0]
Trimmed Array (Zeros Removed): [1 2]


In [16]:
# array creation
import numpy as np
arr=np.array([10])
print("array()->",arr)

print("\n")

arr=np.empty((2,1))
print("empty()",arr)

print("\n")


arr=np.zeros((2,2))
print("zeros()",arr)

print("\n")

arr=np.ones((2,2))
print("ones()",arr)

print("\n")

arr=np.full((2,2), 5)
print("ful()",arr)

print("\n")

arr=np.eye(3)
print("eye()",arr)

print("\n")

arr=np.identity(4)
print("identity()",arr)

print("\n")


arr=np.diag([1,2,3])
print("1D diag()",arr)  # in 1D case it will create an array 

print("\n")

arr=np.diag([[1,2],[3,4]]) 
print("2D diag()",arr) # in 2D case it will extract the diagonal elements 


array()-> [10]


empty() [[0.]
 [0.]]


zeros() [[0. 0.]
 [0. 0.]]


ones() [[1. 1.]
 [1. 1.]]


ful() [[5 5]
 [5 5]]


eye() [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


identity() [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


1D diag() [[1 0 0]
 [0 2 0]
 [0 0 3]]


2D diag() [1 4]


In [17]:
# array with sequence

arr=np.arange(1,10)
print("arrange()",arr)  # return the numpy array with evenly spaced

print("\n")

arr=np.linspace(1,2,num=20)
print("linspace()",arr)  # returns evenly spaced values 

print("\n")


arr=np.logspace(1,2,num=5)
print("logspace()",arr) # returns evenly spaced values based on log base 10

print("\n")

arrange() [1 2 3 4 5 6 7 8 9]


linspace() [1.         1.05263158 1.10526316 1.15789474 1.21052632 1.26315789
 1.31578947 1.36842105 1.42105263 1.47368421 1.52631579 1.57894737
 1.63157895 1.68421053 1.73684211 1.78947368 1.84210526 1.89473684
 1.94736842 2.        ]


logspace() [ 10.          17.7827941   31.6227766   56.23413252 100.        ]




In [18]:
# working with random numbers

arr=np.random.rand()
print("rand()",arr)  # return random float integer b/w 0-1

print("\n")

arr=np.random.randint(10)
print("randint()",arr)  # return random int b/w specified integer 

print("\n")

arr=np.random.randn(1,5)
print("randn()",arr)  # return random array elements b/w specified integer min & max

print("\n")

arr=np.random.uniform(1,5)
print("uniform()",arr)  # Creates an array of random samples from a uniform distribution over a specified interval.

print("\n")


arr=np.random.sample(2)
print("sample()",arr)  # Creates an array of random samples from a normal distribution with specified mean and standard deviation



rand() 0.9939847704017072


randint() 2


randn() [[-1.13582801  0.36516122 -0.09836601  1.04486162  0.57206818]]


uniform() 3.593477680229567


sample() [0.0249128  0.28176242]
