### Airthmatic Operations

In [1]:
import numpy as np

# Addition
arr1 = np.array([100, 200, 300])
arr2 = np.array([10, 20, 30])

print("Addition (using +): ", arr1 + arr2)  # Element-wise addition
print("Addition (using np.add()): ", np.add(arr1, arr2))  # Element-wise addition
# Output:
# Addition (using +):  [110 220 330]
# Addition (using np.add()):  [110 220 330]


# Subtraction
arr1 = np.array([100, 200, 300])
arr2 = np.array([10, 20, 30])

print("Subtraction (using -): ", arr1 - arr2)  # Element-wise subtraction
print("Subtraction (using np.subtract()): ", np.subtract(arr1, arr2))  # Element-wise subtraction
# Output:
# Subtraction (using -):  [ 90 180 270]
# Subtraction (using np.subtract()):  [ 90 180 270]


# Multiplication
arr1 = np.array([100, 200, 300])
arr2 = np.array([10, 20, 30])

print("Multiplication (using *): ", arr1 * arr2)  # Element-wise multiplication
print("Multiplication (using np.multiply()): ", np.multiply(arr1, arr2))  # Element-wise multiplication
# Output:
# Multiplication (using *):  [ 1000  4000  9000]
# Multiplication (using np.multiply()):  [ 1000  4000  9000]


# Division
arr1 = np.array([100, 200, 300])
arr2 = np.array([10, 20, 30])

print("Division (using /): ", arr1 / arr2)  # Element-wise division
print("Division (using np.divide()): ", np.divide(arr1, arr2))  # Element-wise division
# Output:
# Division (using /):  [10. 10. 10.]
# Division (using np.divide()):  [10. 10. 10.]


# Floor Division
arr1 = np.array([100, 200, 300])
arr2 = np.array([10, 20, 30])

print("Floor Division (using //): ", arr1 // arr2)  # Element-wise floor division
print("Floor Division (using np.floor_divide()): ", np.floor_divide(arr1, arr2))  # Element-wise floor division
# Output:
# Floor Division (using //):  [10 10 10]
# Floor Division (using np.floor_divide()):  [10 10 10]


# Modulus
arr1 = np.array([100, 200, 300])
arr2 = np.array([10, 20, 30])

print("Modulus (using %): ", arr1 % arr2)  # Element-wise modulus
print("Modulus (using np.mod()): ", np.mod(arr1, arr2))  # Element-wise modulus
# Output:
# Modulus (using %):  [0 0 0]
# Modulus (using np.mod()):  [0 0 0]


# Power
arr1 = np.array([100, 200, 300])
arr2 = np.array([10, 20, 30])

print("Power (using **): ", arr1**arr2)  # Element-wise power
print("Power (using np.power()): ", np.power(arr1, arr2))  # Element-wise power
# Output:
# Power (using **):  [1.00000000e+20 1.04857600e+46 2.05891132e+71]
# Power (using np.power()):  [1.00000000e+20 1.04857600e+46 2.05891132e+71]


# Absolute
arr = np.array([-100, -200, -300])  # Corrected: Using a single array for absolute value

print("Absolute (using np.abs()): ", np.abs(arr))  # Element-wise absolute value
print("Absolute (using np.absolute()): ", np.absolute(arr))  # Element-wise absolute value
# Output:
# Absolute (using np.abs()):  [100 200 300]
# Absolute (using np.absolute()):  [100 200 300]

Addition (using +):  [110 220 330]
Addition (using np.add()):  [110 220 330]
Subtraction (using -):  [ 90 180 270]
Subtraction (using np.subtract()):  [ 90 180 270]
Multiplication (using *):  [1000 4000 9000]
Multiplication (using np.multiply()):  [1000 4000 9000]
Division (using /):  [10. 10. 10.]
Division (using np.divide()):  [10. 10. 10.]
Floor Division (using //):  [10 10 10]
Floor Division (using np.floor_divide()):  [10 10 10]
Modulus (using %):  [0 0 0]
Modulus (using np.mod()):  [0 0 0]
Power (using **):  [ 7766279631452241920  1152921504606846976 -8070450532247928832]
Power (using np.power()):  [ 7766279631452241920  1152921504606846976 -8070450532247928832]
Absolute (using np.abs()):  [100 200 300]
Absolute (using np.absolute()):  [100 200 300]


### Trignometric Functions

In [2]:
import numpy as np
import math  # Import math for pi

# Trigonometric functions
arr = np.array([30, 45, 90])  # Angles in degrees

print("sin: ", np.sin(np.radians(arr)))  # Sine of angles (converted to radians)
# Output: sin:  [0.5        0.70710678 1.        ]
print("\n")

print("cos: ", np.cos(np.radians(arr)))  # Cosine of angles (converted to radians)
# Output: cos:  [ 0.8660254  0.70710678  0.        ]
print("\n")

print("tan: ", np.tan(np.radians(arr)))  # Tangent of angles (converted to radians)
# Output: tan:  [ 0.57735027  1.         inf]  (inf is infinity because tan(90) is undefined)
print("\n")


arr = np.array([0, -1, 1])  # Values for inverse trigonometric functions

print("arcsin: ", np.arcsin(arr))  # Inverse sine (arcsin)
# Output: arcsin:  [ 0.         -1.57079633  1.57079633]
print("\n")

print("arccos: ", np.arccos(arr))  # Inverse cosine (arccos)
# Output: arccos:  [1.57079633 3.14159265 0.        ]
print("\n")

print("arctan: ", np.arctan(arr))  # Inverse tangent (arctan)
# Output: arctan:  [ 0.         -0.78539816  0.78539816]
# Note: The input for arcsin and arccos should be in the range [-1, 1].
print("\n")


print("hypot: ", np.hypot(3, 4))  # Hypotenuse of a right-angled triangle
# Output: hypot:  5.0
print("\n")


print("radians: ", np.radians(180))  # Convert degrees to radians
# Output: radians:  3.141592653589793
print("\n")


print("degrees: ", np.degrees(math.pi))  # Convert radians (pi) to degrees
# Output: degrees:  180.0
print("\n")


# Hyperbolic functions
print("sinh: ", np.sinh(1))  # Hyperbolic sine
# Output: sinh:  1.1752011936438014
print("\n")

print("cosh: ", np.cosh(1))  # Hyperbolic cosine
# Output: cosh:  1.5430806348152437
print("\n")

print("tanh: ", np.tanh(1))  # Hyperbolic tangent
# Output: tanh:  0.7615941559557649
print("\n")

print("arcsinh: ", np.arcsinh(1))  # Inverse hyperbolic sine
# Output: arcsinh:  0.8813735870195429
print("\n")

print("arccosh: ", np.arccosh(2))  # Inverse hyperbolic cosine (Note: Input should be >= 1)
# Output: arccosh:  1.3169578969248166
print("\n")

print("arctanh: ", np.arctanh(0.5))  # Inverse hyperbolic tangent (Note: Input should be between -1 and 1)
# Output: arctanh:  0.5493061443340549
print("\n")

sin:  [0.5        0.70710678 1.        ]


cos:  [8.66025404e-01 7.07106781e-01 6.12323400e-17]


tan:  [5.77350269e-01 1.00000000e+00 1.63312394e+16]


arcsin:  [ 0.         -1.57079633  1.57079633]


arccos:  [1.57079633 3.14159265 0.        ]


arctan:  [ 0.         -0.78539816  0.78539816]


hypot:  5.0


radians:  3.141592653589793


degrees:  180.0


sinh:  1.1752011936438014


cosh:  1.5430806348152437


tanh:  0.7615941559557649


arcsinh:  0.881373587019543


arccosh:  1.3169578969248166


arctanh:  0.5493061443340549




### Exponential and Logarithmic Functions

In [3]:
import numpy as np

arr = np.array([10, 20])

# Exponentials
print("exp: ", np.exp(arr))      # e raised to the power of each element
# Output: exp:  [2.20264658e+04 4.85165195e+08]
print("\n")

print("exp2: ", np.exp2(arr))     # 2 raised to the power of each element
# Output: exp2:  [1024.   1048576.]
print("\n")

print("expm1: ", np.expm1(arr))    # exp(x) - 1 for each element (more accurate for small x)
# Output: expm1:  [2.20254658e+04 4.85165195e+08]
print("\n")


# Logarithms
print("log: ", np.log(arr))      # Natural logarithm (base e)
# Output: log:  [2.30258509 2.99573227]
print("\n")

print("log2: ", np.log2(arr))     # Base-2 logarithm
# Output: log2:  [3.32192809 4.32192809]
print("\n")

print("log10: ", np.log10(arr))    # Base-10 logarithm
# Output: log10:  [1.         1.30103  ]
print("\n")

print("log1p: ", np.log1p(arr))    # log(1 + x) for each element (more accurate for small x)
# Output: log1p:  [2.39789527 3.04452244]
print("\n")

exp:  [2.20264658e+04 4.85165195e+08]


exp2:  [1.024000e+03 1.048576e+06]


expm1:  [2.20254658e+04 4.85165194e+08]


log:  [2.30258509 2.99573227]


log2:  [3.32192809 4.32192809]


log10:  [1.      1.30103]


log1p:  [2.39789527 3.04452244]




## rounding functions


In [4]:
import numpy as np

arr = np.array([1.72, 2.439, 4.123])

print("round: ", np.round(arr))    # Rounds to the nearest integer (and can specify decimals)
# Output: round:  [2. 2. 4.]
print("\n")

print("around: ", np.around(arr))   # Rounds to the nearest integer (and can specify decimals)
# Output: around:  [2. 2. 4.]
print("\n")

print("rint: ", np.rint(arr))     # Rounds to the nearest integer
# Output: rint:  [2. 2. 4.]
print("\n")

print("floor: ", np.floor(arr))     # Rounds down to the nearest integer
# Output: floor:  [1. 2. 4.]
print("\n")

print("ceil: ", np.ceil(arr))      # Rounds up to the nearest integer
# Output: ceil:  [2. 3. 5.]
print("\n")

print("fix: ", np.fix(arr))       # Truncates towards zero (integer part)
# Output: fix:  [1. 2. 4.]
print("\n")

print("trunc: ", np.trunc(arr))     # Truncates towards zero (integer part)
# Output: trunc:  [1. 2. 4.]
print("\n")

round:  [2. 2. 4.]


around:  [2. 2. 4.]


rint:  [2. 2. 4.]


floor:  [1. 2. 4.]


ceil:  [2. 3. 5.]


fix:  [1. 2. 4.]


trunc:  [1. 2. 4.]




### Statiscal Functions

In [5]:
import numpy as np
from scipy import stats  # Import stats for mode

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print("mean: ", np.mean(arr))  # Arithmetic mean
# Output: mean:  5.5
print("\n")

print("median: ", np.median(arr))  # Middle value when sorted
# Output: median:  5.5
print("\n")

print("mode: ", stats.mode(arr))  # Most frequent value(s)
# Output: mode:  ModeResult(mode=array([1]), count=array([1]))
print("\n")

print("standard deviation: ", np.std(arr))  # Measure of spread
# Output: standard deviation:  2.8722813232690143
print("\n")

print("minimum: ", np.min(arr))  # Smallest value
# Output: minimum:  1
print("\n")

print("arg min: ", np.argmin(arr))  # Index of the smallest value
# Output: arg min:  0
print("\n")

print("maximum: ", np.max(arr))  # Largest value
# Output: maximum:  10
print("\n")

print("arg max: ", np.argmax(arr))  # Index of the largest value
# Output: arg max:  9
print("\n")

print("sum: ", np.sum(arr))  # Sum of all elements
# Output: sum:  55
print("\n")

print("product: ", np.prod(arr))  # Product of all elements
# Output: product:  3628800
print("\n")

print("cumulative sum: ", np.cumsum(arr))  # Cumulative sum of elements
# Output: cumulative sum:  [ 1  3  6 10 15 21 28 36 45 55]
print("\n")

print("cumulative product: ", np.cumprod(arr))  # Cumulative product of elements
# Output: cumulative product:  [      1       2       6      24     120     720    5040   40320
#       362880  3628800]
print("\n")

print("50th percentile: ", np.percentile(arr, 50))  # 50th percentile (median)
# Output: 50th percentile:  5.5
print("\n")

print("25th percentile: ", np.percentile(arr, 25))  # 25th percentile
# Output: 25th percentile:  3.25
print("\n")

print("75th percentile: ", np.percentile(arr, 75))  # 75th percentile
# Output: 75th percentile:  7.75
print("\n")

mean:  5.5


median:  5.5


mode:  ModeResult(mode=np.int64(1), count=np.int64(1))


standard deviation:  2.8722813232690143


minimum:  1


arg min:  0


maximum:  10


arg max:  9


sum:  55


product:  3628800


cumulative sum:  [ 1  3  6 10 15 21 28 36 45 55]


cumulative product:  [      1       2       6      24     120     720    5040   40320  362880
 3628800]


50th percentile:  5.5


25th percentile:  3.25


75th percentile:  7.75




### Linear Algebra Functions

In [6]:
import numpy as np

# Example matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
vector = np.array([2, 3])

# Matrix multiplication
print("np.dot(matrix1, matrix2): ", np.dot(matrix1, matrix2))  # Dot product of two matrices
# Output: np.dot(matrix1, matrix2):  [[19 22]
#  [43 50]]
print("\n")

print("np.matmul(matrix1, matrix2): ", np.matmul(matrix1, matrix2)) # Matrix multiplication
# Output: np.matmul(matrix1, matrix2):  [[19 22]
#  [43 50]]
print("\n")

print("matrix1 @ matrix2: ", matrix1 @ matrix2) # Matrix multiplication (another way)
# Output: matrix1 @ matrix2:  [[19 22]
#  [43 50]]
print("\n")

print("np.dot(matrix1, vector): ", np.dot(matrix1, vector))  # Dot product of matrix and vector
# Output: np.dot(matrix1, vector):  [ 8 18]
print("\n")

# Inverse of a matrix
print("np.linalg.inv(matrix1): ", np.linalg.inv(matrix1))  # Inverse of matrix1
# Output: np.linalg.inv(matrix1):  [[-2.   1. ]
#  [ 1.5 -0.5]]
print("\n")

# Determinant of a matrix
print("np.linalg.det(matrix1): ", np.linalg.det(matrix1))  # Determinant of matrix1
# Output: np.linalg.det(matrix1):  -2.0
print("\n")

# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix1)
print("np.linalg.eig(matrix1):\n eigenvalues:", eigenvalues, "\n eigenvectors:\n", eigenvectors)
# Output: np.linalg.eig(matrix1):
#  eigenvalues: [-0.37228132  5.37228132]
#  eigenvectors:
#  [[-0.82456484 -0.41597356]
#  [ 0.56576745 -0.90937671]]
print("\n")

# Singular Value Decomposition (SVD)
U, S, V = np.linalg.svd(matrix1)
print("np.linalg.svd(matrix1):\n U:\n", U, "\n S:\n", S, "\n V:\n", V)
# Output: np.linalg.svd(matrix1):
#  U:
#  [[-0.52573111 -0.85065081]
#  [-0.85065081  0.52573111]]
#  S:
#  [5.4649857  0.36596008]
#  V:
#  [[-0.40455358  0.9145143 ]
#  [-0.9145143  -0.40455358]]
print("\n")

# Norm of a vector or matrix
print("np.linalg.norm(vector): ", np.linalg.norm(vector))  # Euclidean norm (L2 norm) of vector
# Output: np.linalg.norm(vector):  3.605551275463989
print("\n")

print("np.linalg.norm(matrix1): ", np.linalg.norm(matrix1))  # Frobenius norm (for matrices)
# Output: np.linalg.norm(matrix1):  5.477225575051661
print("\n")

np.dot(matrix1, matrix2):  [[19 22]
 [43 50]]


np.matmul(matrix1, matrix2):  [[19 22]
 [43 50]]


matrix1 @ matrix2:  [[19 22]
 [43 50]]


np.dot(matrix1, vector):  [ 8 18]


np.linalg.inv(matrix1):  [[-2.   1. ]
 [ 1.5 -0.5]]


np.linalg.det(matrix1):  -2.0000000000000004


np.linalg.eig(matrix1):
 eigenvalues: [-0.37228132  5.37228132] 
 eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


np.linalg.svd(matrix1):
 U:
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]] 
 S:
 [5.4649857  0.36596619] 
 V:
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


np.linalg.norm(vector):  3.605551275463989


np.linalg.norm(matrix1):  5.477225575051661




### Array Manipulation Functions

In [7]:
import numpy as np

# I- Changing Shape

arr = np.array([[1, 2, 3], [4, 5, 6]])

print("reshape:\n", np.reshape(arr, (3, 2)))  # Reshape to 3x2
# Output: reshape:
# [[1 2]
#  [3 4]
#  [5 6]]
print("\n")

print("ravel:\n", np.ravel(arr))  # Flatten to 1D
# Output: ravel:
# [1 2 3 4 5 6]
print("\n")

print("flatten:\n", arr.flatten())  # Flatten to 1D (returns a copy)
# Output: flatten:
# [1 2 3 4 5 6]
print("\n")

print("transpose:\n", np.transpose(arr))  # Transpose
# Output: transpose:
# [[1 4]
#  [2 5]
#  [3 6]]
print("\n")

print("swapaxes:\n", np.swapaxes(arr, 0, 1))  # Swap axes 0 and 1 (same as transpose for 2D)
# Output: swapaxes:
# [[1 4]
#  [2 5]
#  [3 6]]
print("\n")

arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) # 3D array for rollaxis example
print("rollaxis:\n", np.rollaxis(arr3d, 0, 2)) # Rolls axis 0 to position 2
# Output: rollaxis:
# [[[1 2]
#   [5 6]]

#  [[3 4]
#   [7 8]]]
print("\n")


# II- Joining Arrays

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print("concatenate:\n", np.concatenate((arr1, arr2), axis=0))  # Along axis 0 (rows)
# Output: concatenate:
# [[1 2]
#  [3 4]
#  [5 6]
#  [7 8]]
print("\n")

print("vstack:\n", np.vstack((arr1, arr2)))  # Vertical stack
# Output: vstack:
# [[1 2]
#  [3 4]
#  [5 6]
#  [7 8]]
print("\n")

print("hstack:\n", np.hstack((arr1, arr2)))  # Horizontal stack
# Output: hstack:
# [[1 2 5 6]
#  [3 4 7 8]]
print("\n")

arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr4 = np.array([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])
print("dstack:\n", np.dstack((arr3, arr4)))  # Depth-wise stack
# Output: dstack:
# [[[ 1  9]
#   [ 2 10]]

#  [[ 3 11]
#   [ 4 12]]]
print("\n")

arr5 = np.array([1, 2, 3])
arr6 = np.array([4, 5, 6])
print("column_stack:\n", np.column_stack((arr5, arr6)))  # Column stack
# Output: column_stack:
# [[1 4]
#  [2 5]
#  [3 6]]
print("\n")


# III- Splitting Arrays

arr = np.array([1, 2, 3, 4, 5, 6])

print("split:\n", np.split(arr, 3))  # Split into 3 equal parts
# Output: split:
# [array([1, 2]), array([3, 4]), array([5, 6])]
print("\n")

print("array_split:\n", np.array_split(arr, 4))  # Split into 4 (near) equal parts
# Output: array_split:
# [array([1, 2]), array([3, 4]), array([5]), array([6])]
print("\n")

arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("hsplit:\n", np.hsplit(arr2d, 3))  # Horizontal split
# Output: hsplit:
# [array([[1],
#        [4],
#        [7]]), array([[2],
#        [5],
#        [8]]), array([[3],
#        [6],
#        [9]])]
print("\n")

print("vsplit:\n", np.vsplit(arr2d, 3))  # Vertical split
# Output: vsplit:
# [array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
print("\n")


# IV- Adding/Removing Elements

arr = np.array([1, 2, 3])

print("append:\n", np.append(arr, [4, 5, 6]))  # Append elements
# Output: append:
# [1 2 3 4 5 6]
print("\n")

print("insert:\n", np.insert(arr, 1, [10, 20]))  # Insert at index 1
# Output: insert:
# [ 1 10 20  2  3]
print("\n")

print("delete:\n", np.delete(arr, 1))  # Delete element at index 1
# Output: delete:
# [1 3]
print("\n")

print("resize:\n", np.resize(arr, (2,2))) # Resizes the array, repeating elements if necessary
# Output: resize:
# [[1 2]
#  [3 1]]
print("\n")


# V- Other Useful Functions

arr = np.array([1, 2, 3])

print("copy:\n", arr.copy())  # Create a copy
# Output: copy:
# [1 2 3]
print("\n")

arr_sq = np.array([[[1]]]) # Example array for squeeze
print("squeeze:\n", np.squeeze(arr_sq))  # Remove single-dimensional entries
# Output: squeeze:
# 1
print("\n")

print("expand_dims:\n", np.expand_dims(arr, axis=0))  # Add a new axis at position 0
# Output: expand_dims:
# [[1 2 3]]
print("\n")

arr_flip = np.array([[1, 2, 3], [4, 5, 6]])
print("flip:\n", np.flip(arr_flip, axis=0)) # Reverses the order of elements along a given axis
# Output: flip:
# [[4 5 6]
#  [1 2 3]]
print("\n")

print("fliplr:\n", np.fliplr(arr_flip)) # Flips array in the left/right direction
# Output: fliplr:
# [[3 2 1]
#  [6 5 4]]
print("\n")

print("flipud:\n", np.flipud(arr_flip)) # Flips array in the up/down direction
# Output: flipud:
# [[4 5 6]
#  [1 2 3]]
print("\n")

arr_rot = np.array([[1, 2], [3, 4]])
print("rot90:\n", np.rot90(arr_rot))  # Rotate by 90 degrees
# Output: rot90:
# [[2 4]
#  [1 3]]
print("\n")

reshape:
 [[1 2]
 [3 4]
 [5 6]]


ravel:
 [1 2 3 4 5 6]


flatten:
 [1 2 3 4 5 6]


transpose:
 [[1 4]
 [2 5]
 [3 6]]


swapaxes:
 [[1 4]
 [2 5]
 [3 6]]


rollaxis:
 [[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


concatenate:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


vstack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


hstack:
 [[1 2 5 6]
 [3 4 7 8]]


dstack:
 [[[ 1  2  9 10]
  [ 3  4 11 12]]

 [[ 5  6 13 14]
  [ 7  8 15 16]]]


column_stack:
 [[1 4]
 [2 5]
 [3 6]]


split:
 [array([1, 2]), array([3, 4]), array([5, 6])]


array_split:
 [array([1, 2]), array([3, 4]), array([5]), array([6])]


hsplit:
 [array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


vsplit:
 [array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


append:
 [1 2 3 4 5 6]


insert:
 [ 1 10 20  2  3]


delete:
 [1 3]


resize:
 [[1 2]
 [3 1]]


copy:
 [1 2 3]


squeeze:
 1


expand_dims:
 [[1 2 3]]


flip:
 [[4 5 6]
 [1 2 3]]


fliplr:
 [[3 2 1]
 [6 5 4]]


flipud:
 [[4 5 6]
 [1 2