### Indexing and Slicing 

In [1]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Indexing (accessing individual elements)
print("arr[0]:", arr[0])      # First element
# Output: arr[0]: 0
print("\n")

print("arr[5]:", arr[5])      # Sixth element
# Output: arr[5]: 5
print("\n")

print("arr[-1]:", arr[-1])     # Last element (negative indexing)
# Output: arr[-1]: 9
print("\n")

print("arr[-2]:", arr[-2])     # Second to last element
# Output: arr[-2]: 8
print("\n")


# Slicing (accessing a range of elements)
print("arr[1:5]:", arr[1:5])    # Elements from index 1 up to (but not including) 5
# Output: arr[1:5]: [1 2 3 4]
print("\n")

print("arr[:5]:", arr[:5])     # Elements from the beginning up to (but not including) 5
# Output: arr[:5]: [0 1 2 3 4]
print("\n")

print("arr[5:]:", arr[5:])     # Elements from index 5 to the end
# Output: arr[5:]: [5 6 7 8 9]
print("\n")

print("arr[2:8:2]:", arr[2:8:2])  # Elements from index 2 up to 8, with a step of 2
# Output: arr[2:8:2]: [2 4 6]
print("\n")

print("arr[::-1]:", arr[::-1])   # Reverse the array
# Output: arr[::-1]: [9 8 7 6 5 4 3 2 1 0]
print("\n")


# 2D Array Indexing and Slicing

arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("\narr2d[0, 1]:", arr2d[0, 1])   # Element at row 0, column 1
# Output: arr2d[0, 1]: 2
print("\n")

print("arr2d[1, :]:", arr2d[1, :])   # Row 1 (all columns)
# Output: arr2d[1, :]: [4 5 6]
print("\n")

print("arr2d[:, 2]:", arr2d[:, 2])   # Column 2 (all rows)
# Output: arr2d[:, 2]: [3 6 9]
print("\n")

print("arr2d[:2, :2]:\n", arr2d[:2, :2])  # Top-left 2x2 submatrix
# Output: arr2d[:2, :2]:
# [[1 2]
#  [4 5]]
print("\n")

print("arr2d[1:, 1:]:\n", arr2d[1:, 1:])  # Bottom-right 2x2 submatrix
# Output: arr2d[1:, 1:]:
# [[5 6]
#  [8 9]]
print("\n")


# Boolean Indexing (using a boolean array to select elements)

bool_arr = arr > 5  # Create a boolean array where True indicates elements > 5
print("\nbool_arr:\n", bool_arr)
# Output: bool_arr:
# [False False False False False False  True  True  True  True]
print("\n")

print("arr[bool_arr]:", arr[bool_arr])  # Select elements where bool_arr is True
# Output: arr[bool_arr]: [6 7 8 9]
print("\n")


# Fancy Indexing (using an array of indices to select elements)

indices = [1, 3, 5]
print("arr[indices]:", arr[indices])  # Select elements at indices 1, 3, and 5
# Output: arr[indices]: [1 3 5]
print("\n")

#For 2D array
indices_row = [0,2]
indices_col = [1,2]
print("arr2d[indices_row,indices_col]:",arr2d[indices_row,indices_col])
# Output: arr2d[indices_row,indices_col]: [2 9]
print("\n")

arr[0]: 0


arr[5]: 5


arr[-1]: 9


arr[-2]: 8


arr[1:5]: [1 2 3 4]


arr[:5]: [0 1 2 3 4]


arr[5:]: [5 6 7 8 9]


arr[2:8:2]: [2 4 6]


arr[::-1]: [9 8 7 6 5 4 3 2 1 0]



arr2d[0, 1]: 2


arr2d[1, :]: [4 5 6]


arr2d[:, 2]: [3 6 9]


arr2d[:2, :2]:
 [[1 2]
 [4 5]]


arr2d[1:, 1:]:
 [[5 6]
 [8 9]]



bool_arr:
 [False False False False False False  True  True  True  True]


arr[bool_arr]: [6 7 8 9]


arr[indices]: [1 3 5]


arr2d[indices_row,indices_col]: [2 9]


