In [1]:
import numpy as np

# I- Padding

arr = np.array([1, 2, 3])

# Constant padding
print("Constant padding:\n", np.pad(arr, pad_width=2, mode='constant', constant_values=0))
# Output: Constant padding:
# [0 0 1 2 3 0 0]
print("\n\n")

# Edge padding
print("Edge padding:\n", np.pad(arr, pad_width=1, mode='edge'))
# Output: Edge padding:
# [1 1 2 3 3]
print("\n\n")

# Reflect padding
print("Reflect padding:\n", np.pad(arr, pad_width=2, mode='reflect'))
# Output: Reflect padding:
# [3 2 1 2 3 2 1]
print("\n\n")

# Symmetric padding
print("Symmetric padding:\n", np.pad(arr, pad_width=2, mode='symmetric'))
# Output: Symmetric padding:
# [2 1 1 2 3 3 2]
print("\n\n")

# 2D array padding
arr2d = np.array([[1, 2], [3, 4]])
print("2D constant padding:\n", np.pad(arr2d, pad_width=1, mode='constant', constant_values=9))
# Output: 2D constant padding:
# [[9 9 9 9]
#  [9 1 2 9]
#  [9 3 4 9]
#  [9 9 9 9]]
print("\n\n")


# II- Trimming

arr_zeros = np.array([0, 0, 1, 2, 3, 0, 0, 0])

print("Trim leading and trailing zeros:\n", np.trim_zeros(arr_zeros))
# Output: Trim leading and trailing zeros:
# [1 2 3]
print("\n\n")

print("Trim leading zeros only:\n", np.trim_zeros(arr_zeros, trim='f'))
# Output: Trim leading zeros only:
# [1 2 3 0 0 0]
print("\n\n")

print("Trim trailing zeros only:\n", np.trim_zeros(arr_zeros, trim='b'))
# Output: Trim trailing zeros only:
# [0 0 1 2 3]
print("\n\n")

Constant padding:
 [0 0 1 2 3 0 0]



Edge padding:
 [1 1 2 3 3]



Reflect padding:
 [3 2 1 2 3 2 1]



Symmetric padding:
 [2 1 1 2 3 3 2]



2D constant padding:
 [[9 9 9 9]
 [9 1 2 9]
 [9 3 4 9]
 [9 9 9 9]]



Trim leading and trailing zeros:
 [1 2 3]



Trim leading zeros only:
 [1 2 3 0 0 0]



Trim trailing zeros only:
 [0 0 1 2 3]



