### Broadcasting

In [1]:
import numpy as np

# I- Changing Shape

arr = np.array([[1, 2, 3], [4, 5, 6]])

print("reshape:\n", np.reshape(arr, (3, 2)))  # Reshape to 3x2
# Output: reshape:
# [[1 2]
#  [3 4]
#  [5 6]]
print("\n\n")

print("ravel:\n", np.ravel(arr))  # Flatten to 1D
# Output: ravel:
# [1 2 3 4 5 6]
print("\n\n")

print("flatten:\n", arr.flatten())  # Flatten to 1D (returns a copy)
# Output: flatten:
# [1 2 3 4 5 6]
print("\n\n")

print("transpose:\n", np.transpose(arr))  # Transpose
# Output: transpose:
# [[1 4]
#  [2 5]
#  [3 6]]
print("\n\n")

print("swapaxes:\n", np.swapaxes(arr, 0, 1))  # Swap axes 0 and 1 (same as transpose for 2D)
# Output: swapaxes:
# [[1 4]
#  [2 5]
#  [3 6]]
print("\n\n")

arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) # 3D array for rollaxis example
print("rollaxis:\n", np.rollaxis(arr3d, 0, 2)) # Rolls axis 0 to position 2
# Output: rollaxis:
# [[[1 2]
#   [5 6]]

#  [[3 4]
#   [7 8]]]
print("\n\n")


# II- Joining Arrays

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print("concatenate:\n", np.concatenate((arr1, arr2), axis=0))  # Along axis 0 (rows)
# Output: concatenate:
# [[1 2]
#  [3 4]
#  [5 6]
#  [7 8]]
print("\n\n")

print("vstack:\n", np.vstack((arr1, arr2)))  # Vertical stack
# Output: vstack:
# [[1 2]
#  [3 4]
#  [5 6]
#  [7 8]]
print("\n\n")

print("hstack:\n", np.hstack((arr1, arr2)))  # Horizontal stack
# Output: hstack:
# [[1 2 5 6]
#  [3 4 7 8]]
print("\n\n")

arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr4 = np.array([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])
print("dstack:\n", np.dstack((arr3, arr4)))  # Depth-wise stack
# Output: dstack:
# [[[ 1  9]
#   [ 2 10]]

#  [[ 3 11]
#   [ 4 12]]]
print("\n\n")

arr5 = np.array([1, 2, 3])
arr6 = np.array([4, 5, 6])
print("column_stack:\n", np.column_stack((arr5, arr6)))  # Column stack
# Output: column_stack:
# [[1 4]
#  [2 5]
#  [3 6]]
print("\n\n")


# III- Splitting Arrays

arr = np.array([1, 2, 3, 4, 5, 6])

print("split:\n", np.split(arr, 3))  # Split into 3 equal parts
# Output: split:
# [array([1, 2]), array([3, 4]), array([5, 6])]
print("\n\n")

print("array_split:\n", np.array_split(arr, 4))  # Split into 4 (near) equal parts
# Output: array_split:
# [array([1, 2]), array([3, 4]), array([5]), array([6])]
print("\n\n")

arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("hsplit:\n", np.hsplit(arr2d, 3))  # Horizontal split
# Output: hsplit:
# [array([[1],
#        [4],
#        [7]]), array([[2],
#        [5],
#        [8]]), array([[3],
#        [6],
#        [9]])]
print("\n\n")

print("vsplit:\n", np.vsplit(arr2d, 3))  # Vertical split
# Output: vsplit:
# [array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
print("\n\n")


# IV- Adding/Removing Elements

arr = np.array([1, 2, 3])

print("append:\n", np.append(arr, [4, 5, 6]))  # Append elements
# Output: append:
# [1 2 3 4 5 6]
print("\n\n")

print("insert:\n", np.insert(arr, 1, [10, 20]))  # Insert at index 1
# Output: insert:
# [ 1 10 20  2  3]
print("\n\n")

print("delete:\n", np.delete(arr, 1))  # Delete element at index 1
# Output: delete:
# [1 3]
print("\n\n")

print("resize:\n", np.resize(arr, (2,2))) # Resizes the array, repeating elements if necessary
# Output: resize:
# [[1 2]
#  [3 1]]
print("\n\n")


# V- Other Useful Functions

arr = np.array([1, 2, 3])

print("copy:\n", arr.copy())  # Create a copy
# Output: copy:
# [1 2 3]
print("\n\n")

arr_sq = np.array([[[1]]]) # Example array for squeeze
print("squeeze:\n", np.squeeze(arr_sq))  # Remove single-dimensional entries
# Output: squeeze:
# 1
print("\n\n")

print("expand_dims:\n", np.expand_dims(arr, axis=0))  # Add a new axis at position 0
# Output: expand_dims:
# [[1 2 3]]
print("\n\n")

arr_flip = np.array([[1, 2, 3], [4, 5, 6]])
print("flip:\n", np.flip(arr_flip, axis=0)) # Reverses the order of elements along a given axis
# Output: flip:
# [[4 5 6]
#  [1 2 3]]
print("\n\n")

print("fliplr:\n", np.fliplr(arr_flip)) # Flips array in the left/right direction
# Output: fliplr:
# [[3 2 1]
#  [6 5 4]]
print("\n\n")

print("flipud:\n", np.flipud(arr_flip)) # Flips array in the up/down direction
# Output: flipud:
# [[4 5 6]
#  [1 2 3]]
print("\n\n")

arr_rot = np.array([[1, 2], [3, 4]])
print("rot90:\n", np.rot90(arr_rot))  # Rotate by 90 degrees
# Output: rot90:
# [[2 4]
#  [1 3]]
print("\n\n")


# Linear Algebra Functions
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
vector = np.array([2, 3])

reshape:
 [[1 2]
 [3 4]
 [5 6]]



ravel:
 [1 2 3 4 5 6]



flatten:
 [1 2 3 4 5 6]



transpose:
 [[1 4]
 [2 5]
 [3 6]]



swapaxes:
 [[1 4]
 [2 5]
 [3 6]]



rollaxis:
 [[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]



concatenate:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]



vstack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]



hstack:
 [[1 2 5 6]
 [3 4 7 8]]



dstack:
 [[[ 1  2  9 10]
  [ 3  4 11 12]]

 [[ 5  6 13 14]
  [ 7  8 15 16]]]



column_stack:
 [[1 4]
 [2 5]
 [3 6]]



split:
 [array([1, 2]), array([3, 4]), array([5, 6])]



array_split:
 [array([1, 2]), array([3, 4]), array([5]), array([6])]



hsplit:
 [array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]



vsplit:
 [array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]



append:
 [1 2 3 4 5 6]



insert:
 [ 1 10 20  2  3]



delete:
 [1 3]



resize:
 [[1 2]
 [3 1]]



copy:
 [1 2 3]



squeeze:
 1



expand_dims:
 [[1 2 3]]



flip:
 [[4 5 6]
 [1 2 3]]



fliplr:
 [[3 2 1]
 [6 5 4]]


