### Views and Copy

In [2]:
import numpy as np

# Create an original array
arr = np.array([1, 2, 3, 4, 5])

# 1. Slicing (Generally creates a view)
arr_slice = arr[1:4]  # Elements from index 1 up to (but not including) 4

print("Original array (arr):\n", arr)
print("\n\n")
print("Slice (arr_slice):\n", arr_slice)
print("\n\n")

print("arr_slice.base is arr:", arr_slice.base is arr)  # Check if it's a view
# Output: arr_slice.base is arr: True (It's a view)
print("\n\n")

arr_slice[0] = 100  # Modify the slice
print("Original array (arr) after modifying slice:\n", arr)  # Original array is changed!
# Output: Original array (arr) after modifying slice:
# [  1 100   3   4   5]
print("\n\n")


# 2. Fancy Indexing (Always creates a copy)
arr_fancy = arr[[1, 3, 4]]  # Select elements at indices 1, 3, and 4

print("Fancy indexed array (arr_fancy):\n", arr_fancy)
print("\n\n")

print("arr_fancy.base is None:", arr_fancy.base is None)  # Check if it's a copy
# Output: arr_fancy.base is None: True (It's a copy)
print("\n\n")

arr_fancy[0] = 200  # Modify the fancy indexed array
print("Original array (arr) after modifying fancy indexed array:\n", arr)  # Original array is unchanged
# Output: Original array (arr) after modifying fancy indexed array:
# [  1 100   3   4   5]
print("\n\n")


# 3. Boolean Indexing (Always creates a copy)
bool_arr = arr > 2  # Create a boolean array
arr_bool = arr[bool_arr]  # Select elements based on boolean array

print("Boolean indexed array (arr_bool):\n", arr_bool)
print("\n\n")

print("arr_bool.base is None:", arr_bool.base is None)  # Check if it's a copy
# Output: arr_bool.base is None: True (It's a copy)
print("\n\n")

arr_bool[0] = 300  # Modify the boolean indexed array
print("Original array (arr) after modifying boolean indexed array:\n", arr)  # Original array is unchanged
# Output: Original array (arr) after modifying boolean indexed array:
# [  1 100   3   4   5]
print("\n\n")


# 4. Reshaping (Sometimes a view, sometimes a copy - depends on memory layout)
arr_reshaped = arr.reshape(5, 1)  # Reshape to a 2D array

print("Reshaped array (arr_reshaped):\n", arr_reshaped)
print("\n\n")

print("arr_reshaped.base is arr:", arr_reshaped.base is arr)  # Check if it's a view
# Output: arr_reshaped.base is arr: True (Likely a view, but could be a copy in some cases)
print("\n\n")


arr_reshaped[0, 0] = 400  # Modify the reshaped array
print("Original array (arr) after modifying reshaped array:\n", arr)  # Original array is changed!
# Output: Original array (arr) after modifying reshaped array:
# [400 100   3   4   5]
print("\n\n")


# 5. flatten() (Always creates a copy)
arr_flattened = arr.flatten()

print("Flattened array (arr_flattened):\n", arr_flattened)
print("\n\n")

print("arr_flattened.base is None:", arr_flattened.base is None)  # Check if it's a copy
# Output: arr_flattened.base is None: True (It's a copy)
print("\n\n")

arr_flattened[0] = 500  # Modify the flattened array
print("Original array (arr) after modifying flattened array:\n", arr)  # Original array is unchanged
# Output: Original array (arr) after modifying flattened array:
# [400 100   3   4   5]
print("\n\n")

# 6. astype() (Always creates a copy)
arr_astype = arr.astype(np.float64)  # Change data type

print("Array after astype (arr_astype):\n", arr_astype)
print("\n\n")

print("arr_astype.base is None:", arr_astype.base is None)  # Check if it's a copy
# Output: arr_astype.base is None: True (It's a copy)
print("\n\n")

arr_astype[0] = 600.0  # Modify the astype array
print("Original array (arr) after modifying astype array:\n", arr)  # Original array is unchanged
# Output: Original array (arr) after modifying astype array:
# [400 100   3   4   5]
print("\n\n")

Original array (arr):
 [1 2 3 4 5]



Slice (arr_slice):
 [2 3 4]



arr_slice.base is arr: True



Original array (arr) after modifying slice:
 [  1 100   3   4   5]



Fancy indexed array (arr_fancy):
 [100   4   5]



arr_fancy.base is None: True



Original array (arr) after modifying fancy indexed array:
 [  1 100   3   4   5]



Boolean indexed array (arr_bool):
 [100   3   4   5]



arr_bool.base is None: True



Original array (arr) after modifying boolean indexed array:
 [  1 100   3   4   5]



Reshaped array (arr_reshaped):
 [[  1]
 [100]
 [  3]
 [  4]
 [  5]]



arr_reshaped.base is arr: True



Original array (arr) after modifying reshaped array:
 [400 100   3   4   5]



Flattened array (arr_flattened):
 [400 100   3   4   5]



arr_flattened.base is None: True



Original array (arr) after modifying flattened array:
 [400 100   3   4   5]



Array after astype (arr_astype):
 [400. 100.   3.   4.   5.]



arr_astype.base is None: True



Original array (arr) after modifyi