In [2]:
import numpy as np

# 1. Creating Structured Arrays

# Define the structured data type
dt = np.dtype([('name', 'S20'), ('age', 'i4'), ('height', 'f8')])  # S20: 20-byte string, i4: 4-byte int, f8: 8-byte float

# Create a structured array (using tuples - recommended)
data = np.array([('Alice', 25, 5.8), ('Bob', 30, 6.2), ('Charlie', 28, 5.9)], dtype=dt)

print("Structured array (from tuples):\n", data)
# Output: Structured array (from tuples):
# [('Alice', 25, 5.8) ('Bob', 30, 6.2) ('Charlie', 28, 5.9)]
print("\n\n")

# From a list of dictionaries (Corrected and Robust using tuples):
data_dicts = [{'name': 'Alice', 'age': 25, 'height': 5.8},
              {'name': 'Bob', 'age': 30, 'height': 6.2},
              {'name': 'Charlie', 'age': 28, 'height': 5.9}]

data_tuples = [(d['name'].encode(), d['age'], d['height']) for d in data_dicts] #Encoding to bytes is crucial
data_from_dicts = np.array(data_tuples, dtype=dt)

print("Structured array from dictionaries (corrected):\n", data_from_dicts)
# Output: Structured array from dictionaries (corrected):
# [('Alice', 25, 5.8) ('Bob', 30, 6.2) ('Charlie', 28, 5.9)]
print("\n\n")


# 2. Accessing Data

print("Names:\n", data['name'])
# Output: Names:
# [b'Alice' b'Bob' b'Charlie']  (Note: These are byte strings)
print("\n\n")

print("Ages:\n", data['age'])
# Output: Ages:
# [25 30 28]
print("\n\n")

print("Heights:\n", data['height'])
# Output: Heights:
# [5.8 6.2 5.9]
print("\n\n")

# Accessing individual records:
print("First record:\n", data[0])
# Output: First record:
# ('Alice', 25, 5.8)
print("\n\n")

print("Bob's age:\n", data[1]['age'])
# Output: Bob's age:
# 30
print("\n\n")


# 3. Modifying Data

data['age'][0] = 26
print("Data after age modification:\n", data)
# Output: Data after age modification:
# [('Alice', 26, 5.8) ('Bob', 30, 6.2) ('Charlie', 28, 5.9)]
print("\n\n")

data[1] = ('Robert', 31, 6.3)  # Modify an entire record
print("Data after record modification:\n", data)
# Output: Data after record modification:
# [('Alice', 26, 5.8) ('Robert', 31, 6.3) ('Charlie', 28, 5.9)]
print("\n\n")


# 4. Sorting and Filtering

print("Sorted by age:\n", np.sort(data, order='age'))
# Output: Sorted by age:
# [('Alice', 26, 5.8) ('Charlie', 28, 5.9) ('Robert', 31, 6.3)]
print("\n\n")

print("People older than 27:\n", data[data['age'] > 27])
# Output: People older than 27:
# [('Robert', 31, 6.3) ('Charlie', 28, 5.9)]
print("\n\n")

Structured array (from tuples):
 [(b'Alice', 25, 5.8) (b'Bob', 30, 6.2) (b'Charlie', 28, 5.9)]



Structured array from dictionaries (corrected):
 [(b'Alice', 25, 5.8) (b'Bob', 30, 6.2) (b'Charlie', 28, 5.9)]



Names:
 [b'Alice' b'Bob' b'Charlie']



Ages:
 [25 30 28]



Heights:
 [5.8 6.2 5.9]



First record:
 (b'Alice', 25, 5.8)



Bob's age:
 30



Data after age modification:
 [(b'Alice', 26, 5.8) (b'Bob', 30, 6.2) (b'Charlie', 28, 5.9)]



Data after record modification:
 [(b'Alice', 26, 5.8) (b'Robert', 31, 6.3) (b'Charlie', 28, 5.9)]



Sorted by age:
 [(b'Alice', 26, 5.8) (b'Charlie', 28, 5.9) (b'Robert', 31, 6.3)]



People older than 27:
 [(b'Robert', 31, 6.3) (b'Charlie', 28, 5.9)]



